### ISSUE TITLE
Reduce number of status updates in backend to 1 or 2 => Follow Magento flow

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#139]
Please reduce the number of status updates to 1 in backend. 

Adyen is logging a lot of information. See image. All in their own status flow. 

But Magento already has enough status codes. These should be followed and re-used

Please see the images: we think this process can really be simplified. (as like other PSP use the Magento flow) 

![example 2](https://cloud.githubusercontent.com/assets/652395/5162540/c20e83be-73c0-11e4-812d-c91f05ab6196.PNG)
![pending payment](https://cloud.githubusercontent.com/assets/652395/5162539/c20d607e-73c0-11e4-9e9f-526cb48e57b1.PNG)

![image](https://cloud.githubusercontent.com/assets/652395/5162545/e7d1866e-73c0-11e4-951c-9103a7e87566.png)

![image](https://cloud.githubusercontent.com/assets/652395/5162581/5c90e0bc-73c1-11e4-8a67-d9c7a87f636b.png)

**Comment by rikterbeek** [comment]
Hi Sean,

For helping a merchant out with problems these comments are very handy. I agree with you that some can be merged. This will be done if we are going to refactor the code for notifications see: #245
I will close this issue the refactor code will be committed under #245

Regards,
Rik ter Beek
Adyen
