### ISSUE TITLE
please create option to disable logging

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#164]
please create option for ADYEN to disable logging

sometimes we have system log on for debugging

but Adyen logs so many items in so many files

that it would be logic to create your own switcht too

This way we can enable logging, but disable adyen logging

Also I dont want this kind of data logged on my server (if not necessary as a security risk)

(ps. many extension have their own switch to toggle logging on an extension level too)

**Comment by rikterbeek** [comment]
Hi Sean,

We are going to add this option. This will be included when we are going to refactor the code for notifications and response url. See #245 I am going to close this issue.

Regards,
Rik ter Beek
Adyen
