### ISSUE TITLE
The CC payment is not been sent to Adyen

### ISSUE THREAD

**Issue by rzamana** [Adyen/magento#179]
We are using the Adyen payment system on our store.

The *boleto* is working fine, but when the CC payment is selected we get "O pagamento foi RECUSADO pela Adyen." ("The payment is REFUSED by Adyen")

Checking on the System Administration on Adyen, the CC payment doesn't have none information about the credit card used. It's like that is not been sent to Adyen.

We already tried with the encryption and without, the result is the equal.

You can see the problem on http://minori.jobboz.com.br

**Comment by adyenpayments** [comment]
Hi Rzamana,

Thanks for letting us know your issue. I have seen your test payments and checkout. In the last test payments I see that you want to use CSE. For CSE the creditcard data is encrypted on the client side. I see that you are using Inovarti One Step Checkout Brasil checkout module. This module has a different way of submitting the order in the front-end. I added some extra logic to support CSE for this module as well. Can you check if this solves your issue ?

Regards,
Adyen

**Comment by rzamana** [comment]
Hi Adyen,

Thanks for the quickly reply, but this doesn't solve the problem.
When I disable the CSE, the problem continues.
The payment data is not been sent to Adyen.
Here is message on the Adyen System Administration:
**Acquirer Response: Refused (Please supply paymentDetails)**

**Comment by rzamana** [comment]
FYI,

Just applied the modifications for the CSE, and the problem continues.

**Comment by adyenpayments** [comment]
Hi Rzamana,

You are using a webserver user that does not have this permission. Try to use the one that is configured on your company account started with "ws@".

Regards,
Adyen

**Comment by adyenpayments** [comment]
Hi Rzamana,

Did this solve your issue ?

Regards,
Adyen

**Comment by rzamana** [comment]
Sorry, but no.

Adyen still doesn't receive the CC information.

**Comment by adyenpayments** [comment]
Hi Rzamana,

Could you send us an email to magento@adyen.com with providing your settings or maybe login details to your magento admin so we can validate if you have the right settings setup ? I see that your site is not working at the moment.

Regards,

**Comment by adyenpayments** [comment]
Hi Rzamana,

We had contact about this issue and support for OSC-Magento-Brasil-6-Pro is not yet completed. The payment object is missing in this checkout. I have raised a ticket on their github repository see https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/issues/69

Regards,
Adyen

**Comment by rikterbeek** [comment]
Hi Rzamana,

We have fix this by doing the CSE on the onchange event of the input fields.
This problem should now be solved.

Regards,
Rik ter Beek
Adyen
