### ISSUE TITLE
how to add sku and order id sold product report in magento?

### ISSUE THREAD

**Issue by pankaju** [Adyen/magento#186]
i want sold product sku's and order id in below
code\core\Mage\Adminhtml\Block\Report\Product\Sold\Grid.php

i tried to below code but showing blank

$this->addColumn('sku', array(
'header' =>Mage::helper('reports')->('SKU'),
'index' =>'sku',
));
$this->addColumn('order_increment_id', array(
'header' => Mage::helper('reports')->('Order'),
'index' => 'order_increment_id',
));

**Comment by adyenpayments** [comment]
Hi pankaju,

How is this related to our module ?

Regards,
Adyen
