### ISSUE TITLE
2.2 Pre fill POS checkout on Payment failed

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#187]
We enter email adddress, then go to POS checkout
When error occurs we go back to CART
=> But now the e-mail field is empty (we are ofcourse still serving the same customer)

Request: E-mail field is pre filled on payment failed

![image](https://cloud.githubusercontent.com/assets/652395/5974510/6e2c6484-a875-11e4-95a3-b95d331a6c89.png)

**Comment by adyenpayments** [comment]
Hi Sean,

Thanks for this enhancement we will look into it.

Regards,
Adyen

**Comment by rikterbeek** [comment]
Hi Sean,

This is implemented.

Regards,
Rik
Adyen
