### ISSUE TITLE
POS checkout name not used

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#188]
Our POS payment method is called "KASSA"

But we dont see this in the CART

I expect to see KASSA on the button

![image](https://cloud.githubusercontent.com/assets/652395/5974532/b2c7e0e6-a875-11e4-8b27-ec02802e49fd.png)

![image](https://cloud.githubusercontent.com/assets/652395/5974537/bbfedbec-a875-11e4-8d50-b1a7f4d1a8ff.png)

**Comment by adyenpayments** [comment]
Hi Sean,

Good point, we can use the title instead of the label. For now you can translate the label through Magento translation.

Regards,
Adyen

**Comment by rikterbeek** [comment]
Hi Sean,

We have implement this.

Regards,
Rik
Adyen
