### ISSUE TITLE
POS Add firstname and surname

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#189]
When using fast checkout we would like to be able to add a NAME (setting optional via backend)

Because when we communicate with the client we like to know their name 

![image](https://cloud.githubusercontent.com/assets/652395/5974560/e6b85480-a875-11e4-89af-31dd006bee81.png)

**Comment by adyenpayments** [comment]
Hi Sean,

Is this something you want to ask during the transaction ? We are looking to an option where the account is automatically created for the shopper (bases on his email) and send him a email that his account is created and he can update his details (billing and shipping information)  at any time.

Regards,
Adyen

**Comment by seansan** [comment]
Both is fine. But if The customer is in front of me as an option I could quickly ask

Imporyant thing is that they should be able to re order online later 






Sent from my iPhone.

On 30 Jan 2015, at 15:17, Adyen bv <notifications@github.com> wrote:

Hi Sean,

Is this something you want to ask during the transaction ? We are looking to an option where the account is automatically created for the shopper (bases on his email) and send him a email that his account is created and he can update his details (billing and shipping information) at any time.

Regards,
Adyen

**Comment by adyenpayments** [comment]
Hi Sean,

True, problem here is how to detect already known customers. We are in contact with a integrator to make this possible for merchants.

Regards,
Adyen

**Comment by seansan** [comment]
yep, that is also an issue

**Comment by rikterbeek** [comment]
Hi Sean,

Think we have solve this issue by autocomplete email and showing then the first and lastname.

Regards,
Rik
Adyen
