### ISSUE TITLE
POS Payment page (after Magento) returns with payment failed after 5 SECS

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#190]
POS Payment page (after Magento) returns with payment failed after 5 SECS

What is the error? Maybe it would be good to show this

![image](https://cloud.githubusercontent.com/assets/652395/5974583/3824b836-a876-11e4-8d58-ae5c22a44fca.png)

**Comment by adyenpayments** [comment]
Hi Sean,

What do you mean with payment failed after 5 seconds,  that it cant' connect to the app if it is not installed?

Regards,
Adyen

**Comment by seansan** [comment]
Probably because we tried on laptop without app. Error message should maybe inform me of that. Cannot find Adyen app. 






Sent from my iPhone.

On 30 Jan 2015, at 15:19, Adyen bv <notifications@github.com> wrote:

Hi Sean,

What do you mean with payment failed after 5 seconds, that it cant' connect to the app if it is not installed?

Regards,
Adyen

**Comment by rikterbeek** [comment]
Hi Sean,

We are not going to add this check because if you add this check you could restrict some tablets (where you think it is a desktop) that have the Adyen app installed.

Regards,
Rik ter Beek
Adyen
