### ISSUE TITLE
2.2 Checkout /w POS on ipad Chrome results in error message (Address missing)

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#191]
Checkout /w POS on ipad Chrome results in error message

In CART we fill out the e-mail address and click POS Checkout .... 

a:5:{i:0;s:274:"Gelieve bezorgingsadres informatie te controleren, Vul alstublieft de voornaam in. Vul alstublieft de achternaam in. Vul alstublieft de straat in. Vul alstublieft de stad in. Vul alstublieft het telefoonnummer in. Vul alstublieft de postcode in. Vul alstublieft het land in.";i:1;s:1599:"#0 /app/code/core/Mage/Sales/Model/Service/Quote.php(298): Mage::throwException('Gelieve bezorgi...')
#1 /app/code/core/Mage/Sales/Model/Service/Quote.php(222): Mage_Sales_Model_Service_Quote->_validate()
#2 /app/code/core/Mage/Sales/Model/Service/Quote.php(238): Mage_Sales_Model_Service_Quote->submitNominalItems()
#3 /app/code/community/Adyen/Payment/controllers/CheckoutPosController.php(66): Mage_Sales_Model_Service_Quote->submitAll()
#4 /app/code/core/Mage/Core/Controller/Varien/Action.php(418): Adyen_Payment_CheckoutPosController->indexAction()
#5 /app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#6 /app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#8 /app/Mage.php(705): Mage_Core_Model_App->run(Array)
#9 /index.php(89): Mage::run('ovh_default', 'store')
#10 {main}";s:3:"url";s:19:"/adyen/checkoutPos/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:11:"ovh_default";}

**Comment by seansan** [comment]
The account you login /w needs to have an address set. As this is normally a system account (user) then they will not always have an address set. 

The error message should be improved to explain this to the users (logged in) - the first reason you think is that the system wants the customer address .... but this is not the case: it needs an address on the system account (logged in user in shop)

**Comment by rikterbeek** [comment]
Hi Sean,

We will look into this. 

Regards,
Rik ter Beek
Adyen

**Comment by rikterbeek** [comment]
Hi Sean,

I think that it throws an error is correct. The error message is a language text so you can change it to whatever you want it to be. language text is : Please check shipping address information. %s

Regards,
Rik
Adyen
