### ISSUE TITLE
Payment transaction failed: 20+ emails and error information is too general

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#194]
Hi, again we had an error that resulted in an error. THis is OK, but ....

** why do we always see this error message 20+ times? (Last time the answer was: this is the client pushing the button, but we had contact and it is not)

** Also the error message is not good enough
- WHY ??? was it refused .. give us the exact reason
- And what is the PAYMENT ID or something so we can dive into these issues

We cannot loose these customers .. and if they call us we need to be able to provide a more precise answer other then "Adyen refused the payment"

Please fix in next verson

Payment transaction failed.
Reason
The payment is REFUSED by Adyen.

Checkout Type
onepage

Address here CUT

Payment Method:
Credit Card

Date & Time:
Feb 1, 2015 6:58:01 AM

![image](https://cloud.githubusercontent.com/assets/652395/5997484/4a434abc-aabc-11e4-9daf-68422605a186.png)

**Comment by adyenpayments** [comment]
Hi Sean,

In a upcoming release of our Platform you will be able to see these specific error messages in our BackOffice with your default permissions. If you want to see this now you have to ask our support to activate this for you support@adyen.com.

By default we give a generic response back. It is possible to enable that you get a Raw Acquirer Result back in the API response. This will provide you more detailed information why a payment failed. We can add this extra information into the module so this is logged in Magento as well. This error messages are raw so we can't show them to the shoppers. This raw Acquirer response is not enabled by default you have to ask our support desk to enable this for you.

We will expand the error message with a pspreference and datetime stamp.

Regards,
Adyen

**Comment by seansan** [comment]
I dont know how RAW the error is ...

But there are some validations on creditcards
- expired
- illegal issuer country
- illegal payment country

etc ...

would be good to know at least a little  ...

**Comment by rikterbeek** [comment]
Hi Sean,

Because of security issues we can not provide details of the reason why the payment failed. You can see it when you log into the Adyen backoffice.

Regards,
Rik ter Beek
Adyen

**Comment by seansan** [comment]
The message is *too* general. Maybe at least some more information (or a
code!). And why is this a huge risk?

**Comment by rikterbeek** [comment]
HI Sean,

The shopper does not need to know the exact reason. The exact reason is restricted and can be found if you login into the Adyen Platform. You can contact support@adyen.com if you want to know more about this.

Regards,
Rik ter Beek
Adyen
