### ISSUE TITLE
Amazon payments

### ISSUE THREAD

**Issue by Mattiaz1988** [Adyen/magento#229]
For conversion improvements we'd like to add to the payment method "login & pay with amazon".
I think it's good improvement also for better user experience into checkout.

**Comment by rikterbeek** [comment]
Hi Mattiaz1988,

Thank you for your message. We encourage you to send a message to support@adyen.com or your account manager. This enables us to provide you dedicated and spot-on support!

Regards,
Rik ter Beek
Adyen
