### ISSUE TITLE
Deletion of cc_type in sales_flat_order_payment

### ISSUE THREAD

**Issue by rivetmichael** [Adyen/magento#234]
Hi,

it seems that a notifications can erase the cc_type with an empty field 'paymentMethod' . It came from \Adyen_Payment_Model_Process::_addAdyenAttributes which doesn't test the value of notification content.

**Comment by rikterbeek** [comment]
Hi Michael,

Thanks for addressing this issue. We have seen that paymentMethod is empty in the CANCEL_OR_REFUND notification. We are going to fix this.

Regards,
Rik ter Beek
Adyen

**Comment by rikterbeek** [comment]
Hi Michael,

This is fixed and will be rolled out to our live platform next thursday.

Regards,
Rik ter Beek
Adyen
