### ISSUE TITLE
Better error handling, communicate reason why payment is refused.

### ISSUE THREAD

**Issue by paales** [Adyen/magento#235]
It currently communicates: "The payment is REFUSED by Adyen.", It would be better if the message is a little bit more informative as to why the payment method is refused. For example:

> Your payment has been refused: Invalid card number

**Comment by rikterbeek** [comment]
Hi Paul,

This is not possible because we do not share this information in the result url because of security reasons.

Regards,
Rik ter Beek
Adyen

**Comment by paales** [comment]
Alright, no problem.
