### ISSUE TITLE
Refactor the code for Notifications and Result URL

### ISSUE THREAD

**Issue by rikterbeek** [Adyen/magento#245]
Refactor code for receiving notification and result url response. There is a lot of overhead in this part of the code this could be a lot cleaner.

- [x] Add option to disable/enable log
- [x] Use different functions for handling notification and result response
- [x] Check if all extra parameters works for all the different modus (HTTP POST, SOAP and JSON)
- [x] Fix this issue #228
- [x] Add an option to ignore the refund notification
- [x] Add event after notifcation is processed (adyen_payment_process_notifications_after)
- [x] Don't cancel an order when invoice is created
- [x] Add an extra check to validate the notification and resultUrl bases on paymentMethod that needs to be the same

**Comment by maximinimus** [comment]
Please make sure you fire the correct event after notification processing (you already have adyen_payment_process_notifications_before)

**Comment by rikterbeek** [comment]
Hi Mathew,

I understand. It will be called adyen_payment_process_notifications_after

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Tomorrow I will fix the two open points.

**Comment by rikterbeek** [comment]
Issue #250 looks like an issue on the Adyen Platform this will be fixed on our side
