### ISSUE TITLE
Reformat code according to Magento ECG coding standard

### ISSUE THREAD

**Issue by paales** [Adyen/magento#251]
Please reformat code according to this standard. A lot of files are a mess and causes commit messages to be very dirty as a result. https://github.com/magento-ecg/coding-standard

Also it might be interesting to install PHPMD to see if there are methods with too much complexity.

**Comment by rikterbeek** [comment]
Hi Paul,

Thanks for this info we are going to look into this.

Regards,
Rik ter Beek
Adyen

**Comment by rikterbeek** [comment]
Hi Paul,

I installed it into my PhpStorm environment. It looks very handy I already made some changes in the code. We will use this standard when programming new logic.

Regards,
Rik
Adyen

**Comment by paales** [comment]
Nice :)
