### ISSUE TITLE
Magento Events

### ISSUE THREAD

**Issue by maximinimus** [Adyen/magento#252]
At the moment you only have one event being dispatched from Model/Process.php - adyen_payment_process_notifications_before

Ideally we would like another event to be dispatched after Process.php has finished - as we need to observe and change order statuses and add to the order history depending on the payment result.

We currently do this ourselves but would it be possible for you to dispatch more events so we don't need to  redo our changes every time you release a new version?

Currently these are the events we have added:
adyen_payment_process_notifications_after - at the end of the _processNotifications function

**Comment by rikterbeek** [comment]
Hi Maximinimus,

I can understand, we are going to add this into the code. I added this feature to this issue #245 

Regards,
Rik ter Beek
Adyen

**Comment by rikterbeek** [comment]
Hi Maximinimus,

This is implemented in this issue #245.

Regards,
Rik
Adyen
