### ISSUE TITLE
Duplicate order issue

### ISSUE THREAD

**Issue by paales** [Adyen/magento#255]
We just received notice that there are two orders placed with exactly the same quote_id. Both orders are paid (paid by Credit Card CSE).

Adyen reference: 4314276176872760 and 1314276176866800. Ideas?

**Comment by rikterbeek** [comment]
Hi Paul,

That is strange because when I order is successful it will close the quote. Could you contact the shopper and ask him what he did ?

Regards,
Rik
Adyen

**Comment by paales** [comment]
This could happen because the customer presses the checkout button twice very fast. I'm sure what actually happened..

**Comment by rikterbeek** [comment]
Hi Paul,

4314276176872760 and 1314276176866800 are different orders. 2903-363213 and 2903-363210. 

Regards,
Rik

**Comment by paales** [comment]
Yes, thats right, they are different orders but are the same quote, which shouldn't happen. It shouldn't be possible to pay a quote (converting it to an order) and paying again for the same order.

**Comment by rikterbeek** [comment]
Hi Paul,

I am closing this issue. If you have specific payment questions you can reach out to us through magento@adyen.com.

Regards,
Rik
Adyen

**Comment by paales** [comment]
@rikterbeek Will do.
