### ISSUE TITLE
Total due doesn't get reduced from order

### ISSUE THREAD

**Issue by paales** [Adyen/magento#257]
Adyen reference, 4714266061628290, order number 1703-352530

Invoice of €99,- is created but the total due of the order isn't changed.
![schermafbeelding 2015-04-02 om 17 18 19](https://cloud.githubusercontent.com/assets/1244416/6966887/4a89d594-d95c-11e4-898d-5ee770c50aaa.png)

I'm not sure if this is a Adyen problem specifically or if this is something in our shop..

**Comment by rikterbeek** [comment]
Hi Paul,

I don't have this issue. If there is a invoice created the Total Due should be zero.
Do you have an invoice for this order ?

Regards,
Rik
Adyen

**Comment by paales** [comment]
Hi Rik,

That is the odd issue, there is an invoice created but it seems the order isn't saved after that. Are you saving the order and invoice in the same transaction? If you are saving it without a transaction it might be possible that we could get in to a state where there is an invoice created but the order couldn't be saved.

**Comment by rikterbeek** [comment]
Hi Paul,

We don't work with transactions. So order is saved and when the notification is received the invoice is created. We use transactionId 1 so Magento knows that it is a online invoice but transactionId is not used by us.

Regards,
Rik
Adyen

**Comment by paales** [comment]
I meant database transactions, not financial transactions ;) (http://stackoverflow.com/questions/7283010/magento-database-transaction)

**Comment by rikterbeek** [comment]
Hi Paul,

We had contact over the phone looks like it is a Magento issue. So I am going to close this issue. Let me know if you have more details about this bug so we can help you to find the problem.

Regards,
Rik
Adyen

**Comment by paales** [comment]
Yes, I'll gather more information.

**Comment by jinalpatel07** [comment]
I am having same issue please do let me know what is issue 
invoice missing for adyen paypal and mastercard when order queue is finished
invoice is created properly for adyen ideal methods
please let me know where is problem
