### ISSUE TITLE
No order gets created when the credit card is invalid.

### ISSUE THREAD

**Issue by paales** [Adyen/magento#258]
To be able to send reminder mails to customers normally a cancelled order gets created when the payment details are invalid, but it seems that Adyen doesn't create an order when the payment method gets created.

**Comment by rikterbeek** [comment]
Hi Paul,

The order is created for HPP payment methods when you redirect to Adyen Platform. If you are using the CreditCard payment then only a successful payment will create an order. This is the main functionality of API integration in Magento. So what do you expect ?

Regards,
Rik
Adyen

**Comment by paales** [comment]
@rikterbeek I'll discuss what a good solution to this issue will be.

**Comment by rikterbeek** [comment]
Hi Paul,

I don't think we can change much in the standard magento flow of API payments.
I close this issue for now if you have something you want to share with us about this you can reopen this.

Regards,
Rik

**Comment by paales** [comment]
@rikterbeek We've build a Quote viewer in the mean time so it still is obvious for the shop owner what happens to all the carts.
