### ISSUE TITLE
hpp_type_label is not fetched correctly

### ISSUE THREAD

**Issue by oblomovx** [Adyen/magento#260]
In \Payment\Model\Adyen\Hpp.php line 80 it says

       $hppTypeLabel =  Mage::getStoreConfig('payments/'.$info->getData('method').'/title');

It should be 

        $hppTypeLabel =  Mage::getStoreConfig('payment/'.$info->getData('method').'/title');

without the s in payments

**Comment by rikterbeek** [comment]
Hi oblomovx,

Many thanks for this information. I changed it directly in the code, it was only in the dev version.

Regards,
Rik
Adyen
