### ISSUE TITLE
Order of payment methods

### ISSUE THREAD

**Issue by oblomovx** [Adyen/magento#262]
It seems the order of payment methods does not follow the order of the skin settings. We would like to set the order, either in the skin options or the magento backend.

**Comment by rikterbeek** [comment]
Hi oblomovx,

You are right in the development version if you change the sort order in Adyen Platform it will not change on Magento side. I added this fix. Be sure that if you change the order you remove the cache becasue result is saved into the cache.

Regards,
Rik
Adyen

**Comment by oblomovx** [comment]
Nice, thanks!
