### ISSUE TITLE
5 credit card payments on a single order.

### ISSUE THREAD

**Issue by paales** [Adyen/magento#265]
I'm not sure if the customer has pressed the checkout button five times or something, but it seems a customers credit card has been subtracted five times.

![schermafbeelding 2015-04-16 om 15 20 35](https://cloud.githubusercontent.com/assets/1244416/7181587/2bd567f8-e44c-11e4-91c4-9e36e7527bfb.png)

![schermafbeelding 2015-04-16 om 15 21 50](https://cloud.githubusercontent.com/assets/1244416/7181610/52ff8610-e44c-11e4-9a15-fb5322d03d17.png)

**Comment by rikterbeek** [comment]
Hi Paul,

Better is to ask this kind of question to magento@adyen.com. We will look into it.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Paul,

The transactions are done separately to our system. Could you check if you have any exceptions in your checkout.

Regards,
RIk
Adyen

**Comment by paales** [comment]
@rikterbeek We haven't experienced the same problem with more recent orders. Unfortunately our logs only go back for a few days, so I can't find what happened with this order.

**Comment by paales** [comment]
I'll reopen an issue when we encounter it.
