### ISSUE TITLE
Dont use rewrite for adding new totals

### ISSUE THREAD

**Issue by paales** [Adyen/magento#269]
```
Adyen_Payment_Block_Sales_Order_Totals
Adyen_Payment_Block_Adminhtml_Sales_Order_Totals
Adyen_Payment_Block_Adminhtml_Sales_Order_Creditmemo_Totals
Adyen_Payment_Block_Adminhtml_Sales_Order_Invoice_Totals
```

Explanation how to add totals without rewriting:
http://turnkeye.com/blog/magento-development-add-total-row-checkout/

**Comment by rikterbeek** [comment]
Hi Paul,

They do exactly the same see:


Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
See section:

So there are 3 blocks (order, invoice, creditmemo) where you need to add your total, we need to rewrite it:

**Comment by paales** [comment]
You're right.. Let me look for a better solution, should be be possible..

**Comment by rikterbeek** [comment]
Hi Paul,

I did not found any other solution where this is not the case. Let me know if there is. I am closing this issue for now.

Regards,
Rik
Adyen
