### ISSUE TITLE
Redirect to correct checkout url for third party checkout

### ISSUE THREAD

**Issue by oblomovx** [Adyen/magento#270]
Currently the checkout to witch to redirect after a failed payment is hardcoded to be checkout/onepage, this should be fetched from the magento settings (by Mage::helper('checkout/url')->getCheckoutUrl() for example), because now it doesn't work correctly when a third party checkout (like Onestepcheckout) is installed.

**Comment by rikterbeek** [comment]
Hi oblomovx,

Sorry for the late response. In our upcoming version (2.3.0) you can select this in the Adyen Default Settings. You can select between checkout/cart and checkout/onepage. Let me know if you are missing a option we can add this.

Regards,
Rik
Adyen

**Comment by oblomovx** [comment]
Hi Rik,

We would like to have the url for the onestep checkout, which by default is /onestepcheckout/. Maybe a text-field in the backend-options would be the most flexible solution.

**Comment by rikterbeek** [comment]
Hi oblomovx,

I think the above change would fix your issue. It is now dynamically getting the cart and checkout url. So I think this will support all checkout modules.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi oblomovx,

Does this solve your issue ?

Regards,
Rik
Adyen

**Comment by oblomovx** [comment]
Yes it does, thanks!

**Comment by rikterbeek** [comment]
Hi oblomovx,

Great, I will close this issue now.

Regards,
Rik
Adyen
