### ISSUE TITLE
Safari privacy setting logs user out after payment page

### ISSUE THREAD

**Issue by ajpevers** [Adyen/magento#275]
# The problem

This problem is reproducible by choosing the following setting in Safari:
![thebad](https://cloud.githubusercontent.com/assets/1489129/7408611/c1fa00a4-ef1e-11e4-8cb1-e2f36ebdd180.png)

The default setting is this:
![thegood](https://cloud.githubusercontent.com/assets/1489129/7408614/c97f63a0-ef1e-11e4-88dc-fcbd9b7ba0a1.png)

So the setting is 'allow cookies from the current website only'.

Now log in, place an order and cancel or finish your payment. Either one works. You will now return to an empty cart page while being logged out.

After using this setting, code like this will not work anymore:
```php
$session = $this->_getCheckout();
$incrementId = $session->getLastRealOrderId();
```

# The solution

Of course logging the user in using the MerchantReference in the url query would be a security risk. However it could be useful to point to a page with an explanation about the consequences of these cookie settings in various browsers. This page can be show when the adyen/process/success page is visited without a session. This is the best solution I've come up with so far to ensure users are not brought into doubt wether or not their payment has succeeded. If there is a better one in your opinion please let me know.

**Comment by rikterbeek** [comment]
Hi Anton,

Thanks for letting us know. I think this is only an issue when the customer cancelled the order or if the order did not succeed. If a order is approved you will always be redirect to the success page.Could you check if this is the case with this setting selected ?

I do not have this option in my safari settings, what version are you using and on what platform ?

Regards,
Rik
Adyen

**Comment by ajpevers** [comment]
Hi Rick,

Unfortunately this happens always. Also after a successful payment. The reason is that as soon as the user leaves the web shop he is logged out. The cookies are not kept after his visit I think.

This happens in the newest version of safari that comes with OSX Yosemity (10.10.3)
![screen shot 2015-05-01 at 13 54 56](https://cloud.githubusercontent.com/assets/1489129/7429858/ab708e84-f009-11e4-88f3-5c138bccb106.png)

**Comment by rikterbeek** [comment]
Hi Anton,

We are redirected the customer to checkout/onepage/success. It looks like Magento does not have something to support this. What we can do is before we redirect use this if statement:

if(!$session->getLastSuccessQuoteId()) {
// session does not exist show page to explain this
}

Could you create a page for this and add this to our module ? You know best what information the shopper needs to have to make the problem clear.

Regards,
Rik
Adyen

**Comment by ajpevers** [comment]
Hi @rikterbeek I have lost track of this issue. I'll assign it to a colleague to investigate if this problem still exists in the latest safari and if there is still the need to fix this.
