### ISSUE TITLE
Error while disabling Billing Agreement #8314282030391188: HTTP Status code 500 received, data disable failed

### ISSUE THREAD

**Issue by paales** [Adyen/magento#278]
I this something that needs to activated on our account or is my request wrong?

Request:
```PHP
[
    [action] => Recurring.disable
    [disableRequest.merchantAccount] => HOEcommerceNL
    [disableRequest.shopperReference] => HOEcommerceNL
    [disableRequest.recurringDetailReference] => 8314282030391188
]
```

**Comment by rikterbeek** [comment]
Hi Paul,

You must use the shopperReference that you used when the recurring contract was saved. In magento module this is always the customerId. So you need to use 1 (in your case) instead of HOEcommerceNL.

Regards,
Rik
Adyen

**Comment by paales** [comment]
Thanks, fixed in https://github.com/ho-nl/Adyen_Payments/commit/9eeb657451d5390eeb6ea790c01ffd43cbe04a41
