### ISSUE TITLE
Capture payment at the moment the order is shipped.

### ISSUE THREAD

**Issue by paales** [Adyen/magento#279]
I believe this should be possible in Magento. When placing an order the Credit Card gets authorized but the full amount doesn't get subtracted from the customers card until the actual shipment is created.

This solves an issue where the amount is already subtracted before the customer has the goods delivered.

**Comment by rikterbeek** [comment]
Hi Paul,

Only AUTHORISATION of a payment is already possible by setting the capture mode to manual. I believe Magento does not have a relationship built in that connect it to the payment method when a order is shipped. Do you think there is ? What we can do is find an event where we can use an observer that creates the capture of the payment.

Regards,
Rik
Adyen
