### ISSUE TITLE
Ability to retry a SEPA payment when the payment failed

### ISSUE THREAD

**Issue by paales** [Adyen/magento#280]
It regularly happens that the customer doesn't have enough credit on their bank account. It should be possible to retry the payment on a later moment. Maybe the system should automatically retry or it should be a manual trigger.

**Comment by rikterbeek** [comment]
Hi Paul,

If there is no money on the account you will get a refusal notification. If you receive this you can wait a couple of days/weeks and then do a new payment request to the adyen platform.

Regards,
Rik
