### ISSUE TITLE
Ability to pay an outstanding order by email

### ISSUE THREAD

**Issue by paales** [Adyen/magento#281]
It should be possible to pay an outstanding order by clicking on a button in the email and go to a page where it is possible for the customer to select their payment method and pay the order.

The payment method could be different from the selected payment method in the order.

I'm not sure what impact this has, but it should be possible to send the customer to Adyen directly and let the customer pay? The Adyen notification updates the order.

**Comment by rikterbeek** [comment]
Hi Paul,

Yes this is possible. I was waiting for this feature to be implemented on the Adyen platform but it has a low priority at the moment. This is something we can build into the magento module.

Regards,
Rik
Adyen

**Comment by tombombadilll** [comment]
This is now implemented since version 2.3.0
