### ISSUE TITLE
Show currency symbol instead of currency code in installments

### ISSUE THREAD

**Issue by LemosT** [Adyen/magento#292]
Greetings, again. This is more of a feature request than an issue, but one of our customers is requiring us to display the currency symbol instead of the currency code in the installments (for example, "R$" instead of "BRL"), and I'm not finding the exact spot to change that.

**Comment by rikterbeek** [comment]
Hi LemosT,

Sorry for the late answer. The currency symbol is inserted here: https://github.com/Adyen/magento/blob/master/app/code/community/Adyen/Payment/Helper/Installments.php#L238

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi LemosT,

To get the symbol you can do: 
$currenctySymbol = Mage::app()->getLocale()->currency($currency)->getSymbol();
after the line $currency = $quote->getQuoteCurrencyCode();

Then change 
$result[(string)$i] = $i."x ".$currency." ".number_format($partial_amount,2);
To:
 $result[(string)$i] = $i."x ".$currenctySymbol . number_format($partial_amount,2);

Regards,
Rik
Adyen

**Comment by LemosT** [comment]
Worked like a charm. Thanks a bunch.
