### ISSUE TITLE
Feature request: show installments on order print outs, confirmation emails and admin panel

### ISSUE THREAD

**Issue by LemosT** [Adyen/magento#294]
Greetings. Our client is requesting that (for the Adyen CC payment method) instead of just the method name, the chosen number of installments be included in the following three places: i) in the file when the customer is printing out the order, ii) in the confirmation email sent to the customer, and iii) in the admin panel, when viewing order details (not the order grid). Would you please advise? Thanks in advance.

**Comment by rikterbeek** [comment]
Hi LemosT,

The number of installments is already shown in the order details page. We can add it to the confimation email and pdf.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi LemosT,

See commit above this will add it to pdf and confirmation email.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Forgot to commit this see below
