### ISSUE TITLE
Success Order with Authorized Payment Adyen Status : N.A

### ISSUE THREAD

**Issue by leohartx** [Adyen/magento#300]
recently, i upgraded Adyen from my client webshop to latest version 2.2.2 and i got this issue. could you please let me know what's happening to my Adyen install ?
![wrong adyen_event_code](https://cloud.githubusercontent.com/assets/980196/7802084/2fa97726-0359-11e5-9940-b36c782c2f33.png)

Thank you,

**Comment by leohartx** [comment]
this is my PSP ref in Adyen test 
PSP Ref 7914325856200474

**Comment by rikterbeek** [comment]
Hi leohartx,

If I go into your account I see that your notifications are not working. Please fix this and you will get the correct status in Magento.

Regards,
Rik
Adyen

**Comment by leohartx** [comment]
hi Rik, how do i fix notification ? i'm sorry that i haven't been working on it for more than a year, just upgraded it recently.

Thanks,
Thanh

**Comment by leohartx** [comment]
oh, i forgot to mention that only Authorized status is not coming to the webshop. Canceled and Declined status showed up when i cancel or use wrong credit card.

**Comment by rikterbeek** [comment]
Hi Leohartx,

See our manual: https://www.adyen.com/dam/jcr:80ea0213-02cd-43aa-8136-459a471d2a0d/MagentoQuickIntegrationManual.pdf I you still have questions about setting up your module please contact magento@adyen.com.

Regards,
Rik
