### ISSUE TITLE
Adyen PSP Reference link when order is paid with link by email

### ISSUE THREAD

**Issue by oblomovx** [Adyen/magento#302]
When a customer has paid with the link in the email, the PSP reference link should be visible in the backend, just like with other payment methods.

**Comment by rikterbeek** [comment]
Hi Oblomovx,

Thanks for your reaction. You are totally right. I added into the info. See commit below.

Regards,
Rik
Adyen

**Comment by oblomovx** [comment]
Thanks for the quick fix!
