### ISSUE TITLE
Authorized and Pending treated identical

### ISSUE THREAD

**Issue by melvyn-sopacua** [Adyen/magento#306]
Observing:

        // Adyen_Payment_Model_Process::_processPostSuccess
        switch ($authResult) {
            case Adyen_Payment_Model_Event::ADYEN_EVENT_AUTHORISED:
            case Adyen_Payment_Model_Event::ADYEN_EVENT_PENDING:
                Mage::log("PAYMENT POST URL BEFORE SAVING STATUS:".$order->getStatus(), Zend_Log::DEBUG, "adyen_notification.log", true);
                /* This shorthand log message doesn't really explain what the issue is. But someone got excited writing it. ;) */

Adyen::Authorized is now falling through and processed the same as Adyen::Pending. Net result is that Ideal payments remain on Pending. For people used to other payment methods, this is a signal postback URL isn't configured right and backoffice has to manually check status in Payment Provider backend.

Looks like a bug to me, but if the log message can be decrypted maybe the problem becomes clear.

**Comment by rikterbeek** [comment]
Hi Melvyn,

Yes that is correct. This is the result url. With the resultUrl only the successpage or cancellation page is showing. It wait for the notification to update the magento status. The logging is already changed in the current github branch that gives you better information.

Regards,
Rik

**Comment by melvyn-sopacua** [comment]
OK, so let me get this straight:

Click to pay => Adyen HPP::ideal() => Response data, status: authorized => Order goes to Pending, customer goes to /checkout/onepage/success.

Out of band process:
- Callback initiated by Adyen, confirming iDeal payment => Order goes to Processing.

This callback URL is hardcoded somewhere? Like Adyen backend? So it won't actually come in when a dev/test environment is used?

**Comment by rikterbeek** [comment]
Hi Melvyn,

Yes that is correct. This is done by the Notifcations. This is a hardcoded url in our backoffice. In our live and test environment so this can be different foreach environment. We can add extra notifications as well if you want to. For magento it is base url of the site and after it this part /adyen/process/ins.
See our manual how to set this up:
https://www.adyen.com/dam/jcr:80ea0213-02cd-43aa-8136-459a471d2a0d/MagentoQuickIntegrationManual.pdf

Regards,
Rik
Adyen
