### ISSUE TITLE
small css issues in 2.2 (maybe template related) - good to check

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#308]
Some small remarks, looks good!

* We needed to add this CSS to make the checkoout buttons work, especially for the CC. Maybe it is template related, but we noticed some pixels missing in outlining. 
* Also when opening the form below there was some spacing missing. 
* "Onthoud deze gegevens" is marked as required. Not so I think
* What is this can be aligned better/maybe bottom
* Check alignment of checkbox and "Onthoud deze gegevens"
* Maybe move the creditcar number entry up, above the name: doesnt this animate the CC logo? Maybe then the it is logical to enter the number first, then the name

Our CSS FYI
/* Small Adyen CSS adjustments */
.checkout-onepage-index #co-payment-form .sp-methods dt label {padding: 0}
.checkout-onepage-index #co-payment-form .sp-methods dt label span {display: initial; font-weight: bold;}
.checkout-onepage-index #p_method_adyen_cc {width: 15px}
.checkout-onepage-index .sp-methods img.adyen-payment-method-icon {margin-right: 11px;}
.checkout-onepage-index .adyen_payment_input_fields {margin-top: 20px !important;}

![image](https://cloud.githubusercontent.com/assets/652395/7986281/f1524126-0ad6-11e5-8112-c1a50c8d6e53.png)

**Comment by rikterbeek** [comment]
Hi Sean,

Always good to optimize the checkout in your theme. It looks good in the normal checkout of magento so think it is related to your theme changes. You are right about save the details does not need to be required I fix this right away. Starting with CreditCard number is indeed better to start with on our HPP we do the same. So changed this as well. See commit below.

Regards,
Rik
Adyen
