### ISSUE TITLE
request for SEPA in backend

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#309]
Is it possible to prese the country if 90% come from 1 country? 
Or can the country be take from the billing address? (a try statement and if no succes no worry we can do it manually
(one click less, more time for other things)

![image](https://cloud.githubusercontent.com/assets/652395/7986868/72116280-0ada-11e5-8c95-1ec113e971c5.png)

**Comment by rikterbeek** [comment]
Hi Sean,

What to do you mean with prese ? This country is already selected based on the country that you have filled in the billing address.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
Hmmm didn't see that working then 

Will check again







Sent from my iPhone.

On 04 Jun 2015, at 17:01, Rik ter Beek <notifications@github.com> wrote:

Hi Sean,

What to do you mean with prese ? This country is already selected based on the country that you have filled in the billing address.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Sean,

Please check again with the latest version.

Regards,
Rik
Adyen
