### ISSUE TITLE
Set status to processing when POS sale is accepted

### ISSUE THREAD

**Issue by oblomovx** [Adyen/magento#311]
Currently, the status is stuck on pending and no invoice is created, so the order can not be completed. We are using POS for the first time now, so I don't know if this is intended behaviour or not, or that our settings are not correct.

**Comment by rikterbeek** [comment]
Hi oblomovx,

This is intended behaviour.  This works the same as for Ecom the order will be updated by the notification that is received. So make sure on your POS merchantAccount you have configured the correct notification url to receive this notification.

Regards,
Rik
Adyen

**Comment by oblomovx** [comment]
Hi Rik,

Thank you for the feedback, I will contact support to try and figure it out.
