### ISSUE TITLE
Order of transactional emails

### ISSUE THREAD

**Issue by oblomovx** [Adyen/magento#313]
Sometimes the order of the transactional emails is wrong: the payment confirmation is sent before the order confirmation is sent. This is confusing for our customers. We would like the order confirmation to be send immediately when an order is placed, regardless of whether the payment succeeds or not. I'm not sure if this is the standard Magento flow or that this is due to the Adyen plugin.

**Comment by rikterbeek** [comment]
Hi oblomovx,

What is the payment confirmation email ? The order confirmation email is send when the payment is made. The default flow is in Magento different from API payments and Gateway (redirect) payments.
Could you be more specific when you have this trouble and what the payment confirmation email is ?

Regards,
Rik
Adyen

**Comment by oblomovx** [comment]
Hi Rik,

With the payment confirmation email I mean the Invoice email. When a payment is completed, the order email and the invoice email are both "sent", but I have noticed that the order email is added to a queue that is sent via cron, while the invoice email is sent directly. This causes the invoice email to arrive earlier in the clients mailbox than the order email. 
Also, some payment methods take a couple of minutes to be processed (paypal for example), during which the customer gets no email at all. 

So, the best behavior in our view would be that an order email is sent immediately after pressing the "Order" button in the checkout. If the customer doesn't pay, he still receives this email. Then, after payment is successful, the customer receives the invoice mail.

**Comment by rikterbeek** [comment]
Hi oblomovx,

I don't understand that the invoice mail can be send but the customer get's no email at all. Could you explain this ?

On the AUTHORISATION notification the order confirmation is send. If you are on auto capture then the invoice will automatically created. If you are on manual capture it will create an invoice when the payment is captured. With the latest version of Magento they have introduce to queue the order confirmation mail. What is the benefit of sending an invoice email to your customer ?

Regards,
Rik
