### ISSUE TITLE
test / dev status and auto invoice

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#318]
Hi, we use auto invoice in our shop and are testing some email delivery problem. Emails are sent when the order is complete (and paid and invoiced). In production this runs fine. 

I noticed that in test modus the auto invoice setting in the config is ignored. Maybe it is an idea to allow for the test flow to follow the same steps? So I would expect the order to also be auto -invoiced /captured in the test modus

Or are we missing something? thanks!

**Comment by rikterbeek** [comment]
Hi Sean,

There should be no differences between our test and live platform. Could you tell me a bit more about this auto invoice ? The invoice is created when the notification is received. Did you setup your notifications on your test account ?

Regards,
Rik

**Comment by seansan** [comment]
>>  Did you setup your notifications on your test account ?
Probably not

**Comment by rikterbeek** [comment]
Hi Sean,

That's why ;)

Regards,
Rik
Adyen
