### ISSUE TITLE
When adding SEPA directdebit in backend - and setting shipping al info is lost

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#322]
Hi, we are entering a SEPA directdebit in backend. Some things we noticed. 

- can you prefill the firstname + lastname (or full customer name) as "bank account holder name" we will change it when necessary (instead of starting blank)
- Is there an IBAN validation used when entering bank number?
- When I enter all the bank details, then continue to the shipping settings and select one => the page reloads and all bank details are gone!! and I have to ask them again ..... the bank details should be stored also. See image 2.

Would be nice if this could be improved a little for the user who haas to fill it out

thanks!

![image](https://cloud.githubusercontent.com/assets/652395/8144579/275582f0-11e5-11e5-8bdc-5c9956cab98f.png)

![image](https://cloud.githubusercontent.com/assets/652395/8144582/3c27d584-11e5-11e5-8bfb-7d5cae5f7b20.png)

**Comment by rikterbeek** [comment]
Hi Sean,

* we can add pre filling this information. We will make this an option
* Yes this is already possible. You can enable or disable this validation in Adyen Sepa settings.
* Looks like Magento backend order creation does not support this. We need to investigate if this is something we can easily integrate in our module.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
>> Looks like Magento backend order creation does not support this. We need
to investigate if this is something we can easily integrate in our module.

Thanks for that. It is just the way order entry works - you fill out
everything and when you are done you click the shipping ...

**Comment by rikterbeek** [comment]
Hi Sean,

Yes I understand, so I find it very strange that they did not built this in. For now select first the shipping method before selecting the payment method.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
This is solved. We are saving the input values into the localStorage of magento
