### ISSUE TITLE
Trying to get property of non-object errors

### ISSUE THREAD

**Issue by leeuwd** [Adyen/magento#326]
The following errors are written to the Magento log file since version 2.3.0:

```
2015-06-18T10:24:49+00:00 ERR (3): Notice: Trying to get property of non-object in app/code/community/Adyen/Payment/controllers/ProcessController.php on line 91
2015-06-18T10:24:49+00:00 ERR (3): Warning: Invalid argument supplied for foreach() in app/code/community/Adyen/Payment/controllers/ProcessController.php on line 91
```

**Comment by rikterbeek** [comment]
Hi Leeuwd,

Looks like your having problems with SOAP. https://github.com/Adyen/magento/blob/develop-2.3.1/app/code/community/Adyen/Payment/controllers/ProcessController.php#L91
Could you debug if $item->additionalData exists in your case. The quick fix is move your notification to HTTP POST or JSON.

Regards,
Rik
Adyen

**Comment by leeuwd** [comment]
It seems the problem indeed occurred because of a SOAP error. Turns out, I need to re-save the Magento Adyen config, so that the password fields are now encrypted (?!).

**Comment by rikterbeek** [comment]
Hi Leeuwd,

Yes they are encrypted in the latest version. Is your problem solved now ?

Regards,
Rik
Adyen

**Comment by leeuwd** [comment]
Re-saved Adyen config but issue seems to still be present.

**Comment by rikterbeek** [comment]
Hi Leeuwd,

There is a upgrade script that does this for you it should have been executed when upgraded. 
see: https://github.com/Adyen/magento/blob/develop-2.3.1/app/code/community/Adyen/Payment/data/adyen_setup/data-upgrade-2.1.2.3-2.1.2.4.php

In Adyen what notification url do you use and what Method have you chosen ?

Regards,
Rik
Adyen

**Comment by leeuwd** [comment]
I use the `/adyen/process/soap` notification URL with SOAP method. Issue occurs for the most standard type of order, with Mastercard payment (did not test other payment methods yet), when returning from Adyen payment page to Magento success page. We use HTTPS.

**Comment by rikterbeek** [comment]
Hi Leeuwd,

That is correct. Somehow your server is not getting all the data. Think you have something misconfigured in the SOAP settings. Could you switch to /adyen/process/json and method JSON to check if this solves your issues.

Regards,
Rik
Adyen

**Comment by leeuwd** [comment]
Issue is no longer present withJSON notifications, so issue can be closed as far as I'm concerned.

**Comment by rikterbeek** [comment]
Hi Leeuwd,

SOAP is not working because you was on the old notification system. If you upgrade to the new system what is recommended it will work.

Regards,
Rik
Adyen
