### ISSUE TITLE
Option to ask which products are shipped / not shipped in POS checkout

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/magento#336]
Hi, we saw this option and this looks very good. 

My question: sometimes we give (ship) the client 2 our of 3 products while they are in our store. We then have 1 item remaining that needs to be shipped later. 

How would we process this in the cart POS checkout?

So the use case is:
Order 3 products in store
Pay 3 using Adyen POS
Issue 2 because we have them directly n the store + ship 2
Backoffice ships 3rd product + sends

![image](https://cloud.githubusercontent.com/assets/11224809/8365900/c1f35706-1b90-11e5-80a6-390e75516b63.png)

**Comment by rikterbeek** [comment]
Hi Sean,

It is not totally clear what you mean. If you don't have the third product in the store it should not be able to select it because the inventory of the product is then zero. Or do you mean something else ?

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
updated issues

**Comment by rikterbeek** [comment]
Magento does not have support for this so that is an limitation of the magento platform.
