### ISSUE TITLE
Payment to specific countries options (like iDeal)

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/magento#338]
Would it be an idea to "show" a payment method if either the billing OR Shipping address contain the country used for validation? (I think it is billing address now only) ... 

95% orders from and for the same country
5% order whilst abroad or on holiday and has it delivered to their country (living abroad, grey nomads)

![image](https://cloud.githubusercontent.com/assets/11224809/8366150/9036d358-1b92-11e5-80c4-7de5ddd40064.png)

**Comment by rikterbeek** [comment]
Hi Sean,

It is only possible to use one country to retrieve the payment methods. We have chosen to use the country in the billing address. Magento does the same with the setting Payment to Specific countries.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
We have made a change so ideal will be shown if it is in the directory lookup. see https://github.com/Adyen/magento/commit/c66574bb13ca31e54edf2fbea3e915a2dc709223
