### ISSUE TITLE
Is iDeal label necessary in checkout?

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#339]
Is iDeal label necessary in checkout?

With the label it states "Choose your bank" above the select and as first option in the selected. Double?

Also the select then can have a css clear+float: left 

![image](https://cloud.githubusercontent.com/assets/652395/8371493/fa917488-1bd8-11e5-85c1-853427a823df.png)

**Comment by rikterbeek** [comment]
Hi Sean,

Yes this is for usability and accessibility.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
Did you understand this comment? the image you see is the end result 

The current situation is that there are two labels 1 above the select and 1 in the select

That is one label too much

**Comment by rikterbeek** [comment]
Hi Sean,

Yes I understood your comment. That is not correct, there is only one label. The second you mentioned is an option in the select box this is not a label. The names are the same, it is just to let the shopper know to select an option here.

Regards,
Rik
Adyen
