### ISSUE TITLE
Javascript error with iDeal payment method / 2.3 version

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#340]
See image, checked using JS validator - this code seems to have multiple issues ... 

![image](https://cloud.githubusercontent.com/assets/652395/8371536/88ce3952-1bd9-11e5-8088-83bb553ffda0.png)

**Comment by robbanl** [comment]
Guessing this issue might be the same as I described in #343

**Comment by rikterbeek** [comment]
Hi,

This is patched and released in version 2.3.1. see https://github.com/Adyen/magento/releases/tag/2.3.1

Regards,
Rik
Adyen
