### ISSUE TITLE
upgrade to latest version IP check on POS checkout gone?

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#341]
Upgrade to latest version IP check on POS checkout gone?

Suddenly the POS checkout button is shown to ALL customers ... I cannot find the IP range setting anymore in the backend

We really need this to show the POS checkout on one location only (and not to everyone who visits our store)

![image](https://cloud.githubusercontent.com/assets/652395/8377830/f0509f8a-1c14-11e5-88a7-16ef6b67f767.png)

**Comment by rikterbeek** [comment]
Hi Sean,

Thanks for letting us know! I see that the filter has moved to Adyen Cash. It should be on both. I fix this in the development branch and will be in the next patch release this week.

Regards,
Rik
