### ISSUE TITLE
GA not tracking Conversions while using Adyen Payment

### ISSUE THREAD

**Issue by santhoshp** [Adyen/magento#342]
Hi,

I am using Magneto 1.8.1.0 version and Payment method is Adyen  
After switching to Adyen Payment, I am not able to track my sales using Google Analytics.
The Orders placed using the Adyen Payment Methods are not recorded into my Google Analytics Conversions.
Can anyone help me to resolve the issue?
Thanks in advance

Thanks
Santhosh

**Comment by rikterbeek** [comment]
Hi santhoshp,

Where do you put your google analytics code ? After a successful payment we will redirect you to the magento success page.

Regards,
Rik
Adyen

**Comment by santhoshp** [comment]
Hi ,

I have put the  google analytics code in success page.But After success full payment,my url is redirected to home page.

My site is multi website in magento.Is there any problem assosiated with that.

Let me know your update.

Thanks
Santhosh

**Comment by rikterbeek** [comment]
HI santhoshp,

That should be no issue. Did you setup the correct result url in the skin ?
If you use the skin for multiple sites you can enable the setting Return url in request to Yes.

Regards,
Rik
Adyen

**Comment by santhoshp** [comment]
Hi,

Ok.The issue is now solved when I changed the return url.

Thanks
Santhosh
