### ISSUE TITLE
Javascript errors in checkout

### ISSUE THREAD

**Issue by robbanl** [Adyen/magento#343]
When having Adyen CC method activated, there is a javascript error in Safari (and I'm guessing other browsers to) saying

    SyntaxError: Unexpected token ']'. Expected ')' to end a argument list.

A close look on the source I can see it's the following line that's complaining.

    Validation.creditCartTypes.set('unionpay', [new RegExp('^62[0-5]\d{13,16}$', new RegExp('^[0-9]{3}$'), true]);

Causing the checkout to not function at all.

Also, another error is

    TypeError: null is not an object (evaluating 'cvcCodeElem.removeClassName')

And the line causing the error

    cvcCodeElem.removeClassName('maximum-length-3');

**Comment by robbanl** [comment]
Looks like they are fixed in develop-2.3.1 branch. Isn't this an error that really shouldn't exist in the master branch and though be hotfixed asap?

**Comment by shirtsofholl** [comment]
Agree

**Comment by rikterbeek** [comment]
Hi robbanl,

Sorry for the late response but I was away. Yes this fix is going to be patched as soon as possible to the master. It is already fixed in the development branch.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
This is patched and released in version 2.3.1. Sorry for the late release.
