### ISSUE TITLE
Suggestion: send order e-mail after creating invoice

### ISSUE THREAD

**Issue by leeuwd** [Adyen/magento#351]
We, and many others, have extended the default Magento `queueNewOrderEmail()` function to add the invoice PDF to the order confirmation e-mail. The Adyen plugin calls that function before creating the invoice, which prevents using the aforementioned functionality.

I suggest a change in the function `_authorizePayment()` in `Adyen_Payment_Model_ProcessNotification`; to put `$this->_prepareInvoice($order);` before `$order->sendNewOrderEmail();`.

**Comment by leeuwd** [comment]
Off course, I can extend your model for now to fix this. This is just a tip/suggestion :)

**Comment by rikterbeek** [comment]
Hi Leeuwd,

Thanks for letting us know. I understand your issue. I moved it so it will be send after the invoice is created.  Could you verifiy if this solves your issue?

Regards,
Rik
Adyen

**Comment by leeuwd** [comment]
My custom solution (extending the model and the function in question) solves the issue. I assume your solution will do the same since it does exactly the same (shuffling function calls).
