### ISSUE TITLE
feature request: extra cost/discount on Magento invoice

### ISSUE THREAD

**Issue by newsjunk** [Adyen/magento#359]
Extra costs and discounts for payment methods are calculated by Adyen. 
But the extra costs do not appear at the invoice. Not a problem for consumers, but for b2b transactions our invoice is off when payment method is paypal or AMEX, two paymenttypes we charge a % extra for. 

Would like to have some options to make the extra costs appear at the (pdf)invoice/ aka the exact amount Adyen charges, is shown.

**Comment by rikterbeek** [comment]
Hi newsjunk,

Do you mean the Extra costs/discounts feature defined in the skin ?
I think it is better to set the extra costs/discount in magento. There are modules available that let you define extra costs/discount on payment methods.

Regards,
Rik
Adyen

**Comment by newsjunk** [comment]
"Do you mean the Extra costs/discounts feature defined in the skin ?:
Yes, exactly. I've looked into modules which can perform surcharges, but the problem is they all seem to work with payment methods 'in magento' as opposed to hosted solutions.

**Comment by rikterbeek** [comment]
Hi Newsjunk,

In the latest version of our extension the Payment methods from our hosted solution are rendered as a separate payment method in Magento. So I think it is now possible to use these extensions.

Regards,
Rik
Adyen

**Comment by newsjunk** [comment]
Hello Rik,

We succeded partially.
- We updated to 2.3.1 and also used 'Fooman Surcharge' as the surcharge module, seems most compatible and most used. 

We can only set surcharges for the payments which have their own 'tab' in the Adyen Module. And do have a name rendered, everything starting with adyen_

So:
**ideal** - yes, possible to add surcharge but we keep this free of charge.
**creditcards** yes, but not possible to add different amounts per cc-brand. Would like to charge Amex more then others because higher costs. 
**paypal** - no succes. Bunch of 'paypal' entries are visible when configuring surcharge. But all 'baked' in magento payment methods.
**other payment methods within magento module** no succes. 

added names of payment methods for clarity
<img width="666" alt="schermafbeelding 2015-07-21 om 13 23 27" src="https://cloud.githubusercontent.com/assets/7307374/8799639/c763d3bc-2fab-11e5-89c0-84d4a9f861c0.png">

**Comment by rikterbeek** [comment]
Hi newsjunk,

The payment methods are rendered in the config as adyen_hpp_.... for example paypal is adyen_hpp_paypal. It has a title it is only not rendered in the backend maybe that is a requirement of the Foorman extension ?

Regards,
Rik

**Comment by rikterbeek** [comment]
Hi Newsjunk,

In latest version we have added fee option for adyen hpp payment methods.

Regards,
Rik
Adyen
