### ISSUE TITLE
Implement new HMAC-SHA256 signing and keys

### ISSUE THREAD

**Issue by rikterbeek** [Adyen/magento#360]
Adyen now have a new method of signing the session data. Implement new method into module and make an option to choose between the two methods.

**Comment by rikterbeek** [comment]
Solve issues with openinvoice payment methods klarna and afterpay now gives error merchant signature incorrect

**Comment by guangmian** [comment]
Merchants Watch*** facing issues with new HMAC in 2.4.0.1, advised to downgrade to 2.4
