### ISSUE TITLE
Update Klarna logo

### ISSUE THREAD

**Issue by leeuwd** [Adyen/magento#362]
Use their latest logo: https://developers.klarna.com/en/nl+php/kpm/logos

**Comment by rikterbeek** [comment]
Hi Leeuwd,

If you enable Adyen OpenInvoice then you will have the klarna latest logos. The logo in Adyen HPP is not yet changed and will be when we are changing the logos see issue #330

Regards,
Rik
Adyen

**Comment by leeuwd** [comment]
It seems that this one is used: `skin/frontend/base/default/images/adyen`, which is not their latest.

**Comment by rikterbeek** [comment]
Using now latest klarna logo it is in the sprite see: http://dev.magento.adyenshop.nl/skin/frontend/base/default/images/adyen/pm_gloss.png

Regards,
Rik
