### ISSUE TITLE
2.3.1. Backend payment request sent, hissoty item has strange link. Was payment email sent?

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#366]
Backend payment request sent, hissoty item has strange link. Was payment email sent?

![image](https://cloud.githubusercontent.com/assets/652395/8696703/ff2e0e3c-2aee-11e5-94d5-940196cb86e5.png)

**Comment by rikterbeek** [comment]
Hi Sean,

Looks like your magento version is not able to show the payment link but only the text. Yes the payment url is in the order confirmation that is send to the customer.

Regards,
Rik

**Comment by seansan** [comment]
why close it? We use magento 1.9.0.1

**Comment by rikterbeek** [comment]
Hi Sean,

Because your question is answered. I think url is not showing because your Magento is not allowing links in the comment history.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
It was not a question / something is wrong it seems

Are you saying: this is a Magento setting to allow or not allow links in
history? (I remember seeing links here before ... )

And if html is not allowed, should the message then not be something else?



thx

**Comment by rikterbeek** [comment]
Hi Sean,

In your screenshot it looks like valid html code but i do not see the full link. I have no idea why it is not showing I have 1.9.0.1 as well and I see the link.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
Hi Rik,

the link seems to be valid html indeed

FYI some remarks
The customer claims not to have received the payment link.
Is there a status overview where we can monitor payment request emails?
(are they sent yes or no)
Also it states "Customer not notified", and though I understand Magento did
not do it => Adyen did! So was the e-mail sent?
And last: is there a way to send a reminder? or does Adyen do this
automatically?
Is the field set to allow html? Or does one need to set this in config
manually? or on attribute level? (we have been using this install since
magento 1.3 so maybe somethings have changed)


[image: Inline image 1]
