### ISSUE TITLE
Order entry via backend -> email with payment request, cannot ship order

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#367]
We entered order entry via backend 
Payment method: email with payment request
The status is "Payment Review"
But we need to give the products today .... problem is that I cannot set the status to shipped
We cannot ship order (probably until after payment)

I think we should be able to ship the order if we need to

**Comment by rikterbeek** [comment]
Hi Sean,

Yes, it is waiting for the payment the we set the order to processing. This is how all our payment methods work there needs to be a payment before creating the invoice. Shipment is not part of our solution only if it is a virtual product then we create a shipment but only after the invoice is created. I don't know if it is even possible to create a shipment before an invoice is created and this will screw up the whole workflow. This is not something we want to be involved in so I think you can best use a third-party module to change the status of an order or create something manually.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
The request is not to create a shipment

The request is to not block the ability to create a shipment (method
canShip() should return true)

**Comment by rikterbeek** [comment]
Hi Sean,

This is the common magento flow. This is only available when invoice is created.

Regards,
Rik
Adyen
