### ISSUE TITLE
Payment refused coming in Adyen

### ISSUE THREAD

**Issue by HemanthRathod** [Adyen/magento#376]
I am getting bellow response:

{"paymentResult_resultCode":"Refused","paymentResult_refusalReason":"010 Not allowed","paymentResult_pspReference":"8814380936587951"}.

Why payment Refused coming???

Please Help me out

Thanks and Regards
Hemanth Rathod

**Comment by rikterbeek** [comment]
Hi HemanthRathod,

You do not have the permissions to do this. For your account on test I activated the permission for CSE. Please use creditcard with CSE see our manual how to set this up: https://www.adyen.com/home/dam/jcr:80ea0213-02cd-43aa-8136-459a471d2a0d/MagentoQuickIntegrationManual.pdf

If you would like to enable this permission on your acount on our live platform, please provide the completed PCI Self Assessment Questionnaire (SAQ) A to the
Adyen Support Team (support@adyen.com). The form can be found here:
https://www.pcisecuritystandards.org/security_standards/documents.php?category=saqs 

Regards,
Rik
Adyen

**Comment by HemanthRathod** [comment]
Hi rik,

Thanks for your reply.

I am using this API to do the Payment 
https://pal-test.adyen.com/pal/adapter/httppost

Everything is fine but in the payment dashboard i getting status as Refused why??

Please help me out
Thanks
HemanthRathod

**Comment by rikterbeek** [comment]
Hi HemanthRathod,

You are not allowed to do the full API please use CSE. 

Regards,
Rik
Adyen

**Comment by HemanthRathod** [comment]
Hi rik, 

Thanks for your reply.

I am using Laravel PHP framework.
Using Direct Api cont we able to do the Create Payment Api call to do the payment??

I am using bellow api to do the payment:
https://pal-test.adyen.com/pal/adapter/httppost


Please reply for this
HemanthRathod

**Comment by rikterbeek** [comment]
Hi HemanthRathod,

You are not using magento ?

See here code example how to use our Payment API with CSE:
https://github.com/Adyen/php/blob/master/2.API/httppost/create-payment-cse.php

And see here how to implement CSE:
https://github.com/Adyen/CSE-JS

For more help about implementation contact support@adyen.com

Regards,
Rik
Adyen

**Comment by HemanthRathod** [comment]
Hi Rik,

I am not using magento.

we need to do payment by cse only?? or through direct api also??

if i use CSE the payment will successfully happens?? or like refused status only??

Please provide details
Thanks
HemanthRathod

**Comment by rikterbeek** [comment]
Hi HemanthRathod,

No, so you do an API with a CSE key included instead of the full card details. Please contact support@adyen.com if you need any more information about this.

Regards,
Rik
Adyen

**Comment by HemanthRathod** [comment]
Hi rik,

Thanks for your reply.

Now payment happening in TEST environment but how to do the payment in LIVE environment??

What steps i need to take to do that??

only API i need to change or anything else??

Please help me out
HemanthRathod

**Comment by rikterbeek** [comment]
Hi HemanthRathod,

If you would like to use CSE on our live platform, please provide the completed PCI Self Assessment Questionnaire (SAQ) A to the
Adyen Support Team (support@adyen.com). The form can be found here:
https://www.pcisecuritystandards.org/security_standards/documents.php?category=saqs

for further questions please mail us at support@adyen.com.

Regards,
Rik
Adyen

**Comment by HemanthRathod** [comment]
Hi Rik,

Totally 9 PCI Self Assessment Questionnaire are there!!. I need to fill all the forms or only one??

Please help me out
HemanthRathod
