### ISSUE TITLE
Problem wirh the SQL files

### ISSUE THREAD

**Issue by elfeffe** [Adyen/magento#379]
I'm trying to make a fresh installation, and I get this error:
I'm in develop-2.3.2

<code>
a:5:{i:0;s:146:"Error in file: "/Users/developer/app/code/community/Adyen/Payment/sql/adyen_setup/mysql4-upgrade-0.0.8-0.0.9.php" - Wrong entity ID";i:1;s:1013:"#0 /Users/developer/app/code/core/Mage/Core/Model/Resource/Setup.php(645): Mage::exception('Mage_Core', 'Error in file: ...')
#1 /Users/developer/app/code/core/Mage/Core/Model/Resource/Setup.php(422): Mage_Core_Model_Resource_Setup->_modifyResourceDb('upgrade', '0.0.1', '2.3.1.2')
#2 /Users/developer/app/code/core/Mage/Core/Model/Resource/Setup.php(327): Mage_Core_Model_Resource_Setup->_installResourceDb('2.3.1.2')
#3 /Users/developer/app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /Users/developer/app/code/core/Mage/Core/Model/App.php(417): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /Users/developer/app/code/core/Mage/Core/Model/App.php(343): Mage_Core_Model_App->_initModules()
#6 /Users/developer/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#7 /Users/developer/index.php(87): Mage::run('', 'store')
#8 {main}";s:3:"url";s:73:"/index.php/admin/cache/index/key/f2713044ec420fa8325f15d54864d874/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}
</code>

It seems to be a bug. The install stops when upgrading fro 0.0.8 to 0.0.9
How to fix that?

**Comment by rikterbeek** [comment]
Hi elfeffe,

First of all, the best thing is to download the stable releases. You can find them here:
The best is to donwload the stable releases:
https://github.com/Adyen/magento/releases

In the file of the error there is nothing special,it only remove and adds attributes. see:
https://github.com/Adyen/magento/blob/develop-2.3.2/app/code/community/Adyen/Payment/sql/adyen_setup/mysql4-upgrade-0.0.8-0.0.9.php

Maybe you have some problems with attributes in your magento installation ?

Regards,
Rik
Adyen

**Comment by elfeffe** [comment]
Yes, I changed to master.
Anyway, as far as I know, I don't have any problems with attributes.

**Comment by rikterbeek** [comment]
Hi elfeffe,

I see that we have in our stable release a try and catch arround this see:
https://github.com/Adyen/magento/blob/2.3.1/app/code/community/Adyen/Payment/sql/adyen_setup/mysql4-upgrade-0.0.8-0.0.9.php

So i advise you to download our stable release version 2.3.1 from https://github.com/Adyen/magento/releases/tag/2.3.1.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Elfeffe,

Did this solve the issue ?

Regards,
Rik
Adyen

**Comment by elfeffe** [comment]
yes,  thank you

**Comment by rikterbeek** [comment]
Hi Elfeffe,

That is great!  I will close this issue now.

Regards,
Rik
Adyen
