### ISSUE TITLE
Undefined offset on installment calculation

### ISSUE THREAD

**Issue by viniciusrtf** [Adyen/magento#380]
Many  installments configurations like the attached one throws "Undefined offset" notices in PHP, and prevent all payment methods to display (not only Adyen_Payment).

![captura de tela de 2015-08-11 10 53 36](https://cloud.githubusercontent.com/assets/2480680/9199397/88a6fa96-4018-11e5-9b70-b60723221202.png)

![captura de tela de 2015-08-11 11 05 38](https://cloud.githubusercontent.com/assets/2480680/9199480/ef0606c4-4018-11e5-80b2-3cd8d0fbc660.png)

To prevent this problem I inserted ternary assignments with isset() conditionals on affected lines of:
- Adyen/Payment/Helper/Installments.php (line 230)
- Adyen/Payment/Model/Sales/Quote/Address/Total/PaymentInstallmentFee.php (line 74)

But instead of submitting a pull request I would ask you to look at those methods, so you can decide if this for loop is correct and/or necessary.

I also would like you to take a look on the interest calculation that comes right after this issue in both files. Is it correct to hardcode a constant index in $installment[3] ? I know I didn't configured any interest rate in my installments config example, but I tested that and if I configure the last row with currency -> BRL, amount -> empty, max -> 6, interest -> 1, the interest rate of 1% will not apply for 6 installments.

**Comment by rikterbeek** [comment]
Hi Vinícius,

Could you be more specific, when did you have this error what is your installment configuration ?

Regards,
Rik
Adyen

**Comment by viniciusrtf** [comment]
Yes, of course Rik. I edited my comment with new information.

Regards!

**Comment by rikterbeek** [comment]
Hi Vinícius,

You need to configure all installments. So start with 1 then 2 and 3. you need to define this otherwise you have this issue.

Regards,
Rik
Adyen

**Comment by viniciusrtf** [comment]
Hi Rik,

The documentation (screenshot attached) should be updated then. 

![captura de tela de 2015-08-11 11 48 29](https://cloud.githubusercontent.com/assets/2480680/9200585/e979de32-401e-11e5-8a0b-2ea31572c781.png)

Anyway, I'm still concerned about the way the interest rate is configurable in rows 1-3 in Magento Admin, but the code will only consider row 4 as applicable.

**Comment by rikterbeek** [comment]
Hi Vinícius,

You are right we need to update that manual. You need to fill in a percentage rate so 1 or 1.2 or whatever.

Regards,
Rik
Adyen

**Comment by viniciusrtf** [comment]
After a while reading the code I could understand why configuring all statements is important to the proper interest rate calculation. It would need considerably more lines of code and higher complexity to correctly calculate interest rates for each installment if we would configured like the manual.
