### ISSUE TITLE
403 Error when placing cash order

### ISSUE THREAD

**Issue by oblomovx** [Adyen/magento#384]
When I try to place an order from the backend with the cash payment method I get the following error:

HTTP Status code 403 received, data message=Not+allowed&errorType=security&status=403&errorCode=010

**Comment by rikterbeek** [comment]
Hi oblomovx ,

By default this payment method is not activated on your account.
Could you please contact magento@adyen.com and ask to add Cash payment method. Don't forget to ask for what merchantAccount you want this and if you want this for test or live.

Regards,
Rik
Adyen
