### ISSUE TITLE
release 2.3.2 Different authorisation codes

### ISSUE THREAD

**Issue by oblomovx** [Adyen/magento#385]
Since I installed the 2.3.2 I have the following problem:
Some orders are set to the adyen status AUTHORISED, others to AUTHORISATION : TRUE . When orders are set to AUTHORISED, the magento status of the order is not set to processing, which is incorrect.

**Comment by rikterbeek** [comment]
Hi oblomovx,

What version of the module are you using? What payment method is used ?
Both can be good but if you are on auto capture it should update to processing if you have received the AUTHORISATION in both cases.

Regards,
Rik
Adyen

**Comment by oblomovx** [comment]
It occurs with different payment methods: ideal, mastercard and visa. It seems there are two notifiactions sent:

14 aug. 2015 12:36:29|Wachtende
Klant niet ingelicht 
Adyen HTTP Notification(s): 
eventCode: AUTHORISATION 
pspReference: -removed-
paymentMethod: ideal 
success: true

14 aug. 2015 12:36:30|
Klant niet ingelicht 
Adyen Result URL Notification(s): 
authResult: AUTHORISED 
pspReference: 4814395485365582 
paymentMethod: ideal

The status is set to the last one that is received.

**Comment by rikterbeek** [comment]
Hi oblomovx,

No, the AUTHORISATION  is the only notification. This will update the order. The AUTHORISED is the resulturl. So when the customer is returned if the payment is successful (in this case) it will show the success page but nothing more. It could be that the notification is sometimes faster then the resulturl.

Regards,
Rik
Adyen

**Comment by oblomovx** [comment]
Ok, I just noticed that the "Order status authorised payment" setting was set to "Processing". I unset this setting, and will monitor if this fixes it.

**Comment by rikterbeek** [comment]
Hi oblomovx,

This should be on processing or do you want to have a different flow in magento ?

Regards,
Rik
Adyen

**Comment by oblomovx** [comment]
Hi Rik,

I have created a support ticket as this seems specific to our installation.

**Comment by rikterbeek** [comment]
Hi oblomovx,

That is great. We will help you this way. I will close this issue for now.

Regards,
Rik
Adyen
