### ISSUE TITLE
DE_de translation error, missing quote

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#393]
You have cancelled the order. Please try again", "Sie haben den Auftrag storniert. Bitte versuchen Sie es erneut"

should be

"You have cancelled the order. Please try again", "Sie haben den Auftrag storniert. Bitte versuchen Sie es erneut"

see char 1

**Comment by rikterbeek** [comment]
Hi Sean,

Thanks for letting us know. You can always do the changes by yourself and do a pull request.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
sorry that is true; was almost to small an error to report ....
