### ISSUE TITLE
German text in backend SEPA

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#394]
Hi, we see payment from our DE website in the backend which is set to EN with a german text. 

Should this not be English? (like the backend)

![image](https://cloud.githubusercontent.com/assets/652395/9523972/c554d352-4cdc-11e5-8ce6-8aab8e016176.png)

**Comment by rikterbeek** [comment]
Hi Sean,

This text is not coming from our module. This is coming from core of magento.

Regards,
Rik
Adyen
