### ISSUE TITLE
SEPA direct debit payment issue on invoice PDF

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#399]
SEPA direct debit payment issue on invoice PDF

Please see attachment

![image](https://cloud.githubusercontent.com/assets/652395/9634269/25ef42c0-5191-11e5-8f98-d94beb3c5f82.png)

**Comment by rikterbeek** [comment]
Hi Sean,

Thanks for letting us know about this issue. The above change will fix your issue.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
thx. Is there an ETA on next version? we will upgrade it then

**Comment by rikterbeek** [comment]
Hi Sean,

Yes, next Monday.

Regards,
Rik
