### ISSUE TITLE
SEPA direct debit issue where no confirmation send to client

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#402]
SEPA direct debit issue where no confirmation send to client

When we have new orders with Pending Payment or Payment Review

The customer is not informed of the order (and hence calls us, or even places a new order ....)

How would we tackle this? I don't think there is an easy way of doing this ... or should Adyen activate a certain email template when these orders occur - just to reminder the client that the order was received but that full order details will be received after the payment is received

thanks, Sean

**Comment by seansan** [comment]
We have this to YES

Apparently I have to email support yes?

And what is the email? where is the email coming from that is sent?

[image: Inline image 1]

**Comment by rikterbeek** [comment]
Hi sean,

Ok do you have pending sepa notification turned on as well on all your merchant accounts in adyen platform as well?

Order confirmation is send from magento platform. The mail send from the adyen platform is detail payment information. If you want to know more about this check out our mail manual or contac magento@adyen.com

Regards,
Rik
Adyen

**Comment by seansan** [comment]
>> Ok do you have pending sepa notification turned on as well on all your
merchant accounts in adyen platform as well?
I dont know. What does this do?

>> Order confirmation is send from magento platform.
Maybe this is not functioning then because when a New Pending Payment is
created there is no email to the client ... or am I missing another
configuration step somewhere?

**Comment by seansan** [comment]
Sorry to bother you again

You say "if the payment is placed" but this sounds like the money was paid
-> in this case we do see the order confirmation

OUr question is for the time between 1 and 2:

1. Customer places SEPA debit order
2. Bank tries to deduct the money (waiting - average 2-3 days)
3. Money was taken, order is NEW

THe customer expects some kind of confirmation that we did receive the
order and SEPA is in progress

**Comment by rikterbeek** [comment]
Hi Sean,

with placed I meant register the payment in adyen. Then we send out the PENDING notification and if you have the setting "Send order confirmation email for Bank Transfer/SEPA" enabled it will send the order confirmation mail.

Regards,
Rik
