### ISSUE TITLE
Cancelling in-progress SEPA direct debits

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#403]
Maybe a strange situation, but we want to cancel an in-progress SEPA direct debit

Client placed two identical orders

Now wants to cancel number 2; but this is SEPA

Normal cancel does not work
And there is no invoice to credit

thanks

**Comment by rikterbeek** [comment]
Hi sean,

There is nothing to cancel because payment is not paid. You can just cancel one order in magento and ask the shopper to pay only one order.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi sean,

Sorry i thought you mean bank transfer. Don't you see the payment in adyen backoffice? 

Regards,
Rik

**Comment by seansan** [comment]
Status "Payment Review"

I cannot cancel
and I cannot credit note

So how does one "stop" a direct Debit paymen that is in progress

**Comment by rikterbeek** [comment]
Hi Sean,

It is visable in our backoffice as received. You can there cancel this till midnight.
for more information about this you can contact us at support@adyen.com

Regards,
Rik
Adyen

**Comment by seansan** [comment]
Can we not do this with a CANCEL proces in Magento? We work in Magento
