### ISSUE TITLE
Error on pdf Payment block info

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#404]
Payment block info on pdf invoice is this error instead of payment info

#1 Gratis verzending - PostNL Adyen_Payment_Block_Info_Hpp[Mage_Core_Block_ Template]#000000004a7cb728000000002a5dfa7e#-> (Totaal Verzendkosten € 0,00) fetchView('frontend/base/de...') called at [app/code/core/Mage/Core/Block/Template.php:2
78] #2 Adyen_Payment_Block_Info_Hpp[Mage_Core_Block_ Template]#000000004a7cb728000000002a5dfa7e#-> renderView() called at [app/code/core/Mage/Core/Block/Template.php:2
92] #3 Adyen_Payment_Block_Info_Hpp[Mage_Core_Block_ Template]#000000004a7cb728000000002a5dfa7e#-> _toHtml() called at [app/code/core/Mage/Core/Block/Abstract.php:9
19] #4 Adyen_Payment_Block_Info_Hpp[Mage_Core_Block_ Abstract]#000000004a7cb728000000002a5dfa7e#-> toHtml() called at [.modman/magento/app/code/community/Adyen/Pay ment/Block/Info/Hpp.php:37] #5 Adyen_Payment_Block_Info_Hpp#000000004a7cb728 000000002a5dfa7e#->toPdf() called at [app/code/local/Mage/Sales/Model/Order/Pdf/Ab stract.php:318] #6 Fooman_EmailAttachments_Model_Order_Pdf_Order [Mage_Sales_Model_Order_Pdf_Abstract]#0000000 04a7cb7e7000000002a5dfa7e#->insertOrder(&Zend _Pdf_Page#000000004a7cb706000000002a5dfa7e#, &Mage_Sales_Model_Order#000000004a7cb65600000 0002a5dfa7e#, true) called at [app/code/community/Fooman/EmailAttachments/M odel/Order/Pdf/Order.php:59] #7 Fooman_EmailAttachments_Model_Order_Pdf_Order #000000004a7cb7e7000000002a5dfa7e#->getPdf(ar ray(&Mage_Sales_Model_Order#000000004a7cb6560 00000002a5dfa7e#)) called at

**Comment by seansan** [comment]
Image

![image](https://cloud.githubusercontent.com/assets/652395/9700624/b43928f0-5409-11e5-93fc-519f089a3675.png)

**Comment by rikterbeek** [comment]
Hi sean,

This is related to your other ticket issue #405

Regards,
Rik
Adyen
