### ISSUE TITLE
Is it possible to also enable the template on frontend?

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/magento#405]
There are extension that do some magic during checkout: like attaching the invoice as pdf. Not very uncommon. Because the adyen payment pdf templates are configured as backend type we now always get errors; and template files cannot be found

2015-09-05T16:49:13+00:00 DEBUG (7): 05-09-2015 18:49:13 Missing template file:frontend/base/default/template/adyen/pdf/hpp.phtml

Is it a big problem to also enable the template files on frontend so it works for everybody? Seems like a quick win

**Comment by rikterbeek** [comment]
Hi Sean,

We have already discussed this in this ticket #182

Regards,
Rik
Adyen
