### ISSUE TITLE
2.4.0 Notice: Undefined index: code_alt

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#408]
Found this in log when editing settings in backend

2015-09-08T08:21:15+00:00 ERR (3): 08-09-2015 10:21:15 Notice: Undefined index: code_alt  in /home/domains/domain.com/public_html/.modman/magento/app/code/community/Adyen/Payment/Helper/Data.php on line 58

**Comment by rikterbeek** [comment]
Hi Sean,

Could you check if code_alt is available for all creditcard methods in your config.xml ?
https://github.com/Adyen/magento/blob/develop-2.3.2/app/code/community/Adyen/Payment/etc/config.xml#L447

Regards,
Rik

**Comment by seansan** [comment]
Yes it is

[image: Inline image 1]

**Comment by rikterbeek** [comment]
Can you clear your cache and logs and check again ?

**Comment by seansan** [comment]
Yes. always after update.

But I will monitor this and check it later

**Comment by seansan** [comment]
We still see this error. Every 1 minute in our logs!!

**Comment by rikterbeek** [comment]
Hi Sean,

It is a notice so not a big thing but still i can not understand it because ccTypes all have this parameter.
Could you debug by printing out the $_types variable and check if all the items of the xml are in the array ?

Regards,
Rik
Adyen
