### ISSUE TITLE
SEPA missing translations, that do exist for CC payments

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#416]
SEPA missing translations, that do exist for CC payments

We are missing both NL and DE; they also do not exist in the translations file

![image](https://cloud.githubusercontent.com/assets/652395/9929339/54d939dc-5d2c-11e5-9184-ed90c5ce732c.png)

**Comment by rikterbeek** [comment]
Hi Sean,

thanks for letting us know we will add this in the near future.

Regards,
Rik
Adyen
