### ISSUE TITLE
Error with SEPA debit and REFUND/Credit memo

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#422]
We see Error with SEPA debit and REFUND/Credit memo

1. Create payment SEPA debit & let is clear
2. Create refund (when this setting is not allowed in Adyen)
3. Magento creates update: "partial refund FALSE"
Suggestion: I would change this error message to something like "REFUND REFUSED" which stands out more
Suggestion: Also no error message was shown when creating the credit memo
4. in last step the credit memo does! exist - it seems to be created; 
Error: it should not create the credit memo because there was no refund

Please confirm (this is difficult for us to test)

**Comment by rikterbeek** [comment]
Hi Sean,

During the credit memo process we have only a option to do an api call. Our api call can not give back directly if the refund has succeed or not we do this trough a notification. The API result is giving back received. Magento thinks the refund went well and set the order to refunded but the refund could fail. Example is that you do not have enough amount on your account.

Regards,
Rik
Adyen
