### ISSUE TITLE
Klarna won't work if there are custom gender labels

### ISSUE THREAD

**Issue by WPEwald** [Adyen/magento#423]
If customer has edited the Gender customer attribute with their own labels (for example 'Man' instead of 'Male' in case of a Dutch store), Klarna won't work anymore because a getOptionText is used which returns the label for the store. 
I'm not sure what would be a good solution, maybe a hardcoded list (as Klarna demands either MALE or FEMALE) would suffice.
This is specifically the case in https://github.com/Adyen/magento/blob/develop/app/code/community/Adyen/Payment/Model/Adyen/Openinvoice.php method getOptionalFormFields where shopper.gender is set (three instances).

**Comment by rikterbeek** [comment]
Hi Ewald,

What I think is that you should never change the option text in the database but add a translate function around this value in the templates. That is what we have done in our module. But we have now seen that multiple merchants have changed this value in the database causing issues with the integration to Klarna. So I will make a change that we always send Male or Female to klarna.

Regards,
Rik
Adyen
