### ISSUE TITLE
If the adyen notification is earlier than the API then a NEW order is set back to status pending

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/magento#425]
If the adyen notification is earlier than the API then a NEW order is set back to status pending

Create order
Payment
in same cases the notification is faster than API
then we see in the flow an order which paid->new .... and then a little later -> pending payment
Rarely happens, but should not

![unnamed](https://cloud.githubusercontent.com/assets/11224809/10365195/b285c870-6dc1-11e5-89ab-461bded0357b.png)

**Comment by oblomovx** [comment]
We seem to have the same issue sometimes

**Comment by shirtsofholl** [comment]
Thanks for confirming.

Already reported this with adyen support. But they did not feel the need to
log it themselves



Wij maken het graag voor je in orde.

met groeten, Mark


_________________________________________________________
info@shirtsofholland.com | KvK 60827378 | https://shirtsofholland.com

[image: ShirtsofHolland - dé specialist in Oranje kleding]
<http://shirtsofholland.com/>

2015-10-08 14:55 GMT+02:00 oblomovx <notifications@github.com>:

**Comment by rikterbeek** [comment]
Hi,

I do not understand the issue. The result of the api does not set the status of the order.
In your screenshot I see that the result url is not changing the status. Could you explain me in more detail what is going wrong?

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
The last event kicks back the order in status: pending, I know you dont see it in the log - but this is what is happpening

In more detail:
So we have an order /w status new
That a second later has status pending again
And when we look up the order in Adyen we see it is paid
Then we go back to Magento and set the status manually back to New

Maybe @oblomovx has a better description

**Comment by rikterbeek** [comment]
Hi,

Can you see what is setting this to pending? If I look in your comment history I do not see this.

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
Hi, no I cannot see more in detail. 

Maybe you can check messages and notifications sent and the order of the messages in system? 
PSP = 4314442397374370

There is just not more information to give unless there is a detailed log somewhere that I can give you

**Comment by rikterbeek** [comment]
Hi Sean,

Can you give me a screenshot of the comment history where this is the case. In you screenshot above the issue you described is not the case. Here the status is going from "Nog betalen" to "Nieuw" what is correct.

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
There is not more to show .... 

- This is what the log shows there is not more information
- And the order had status 'nog betalen' 

So there is an disrepancy: that is why we logged this

**Comment by questionmark78** [comment]
We had a similar issue. 
The comment history shows a normal flow, but the in sales_flat_order status and state are not updated (or reset to pending) and sale_flat_order_grid status is pending. We have seen it only once now, with a Mastercard payment.

**Comment by rikterbeek** [comment]
Hi Guys,

It looks like it matters when the notification is received. When we send it to soon it looks like Magento has problems with this. Solution is to add all notification to the queue and execute them later. I have set it to 5 minutes. See the fix here: #458 we are going to optimize this by cleaning up the queue if order does not exists.

Regards,
Rik
Adyen
