### ISSUE TITLE
Invoice is created when notification has a "success: false" status

### ISSUE THREAD

**Issue by TamasJozsefSzabo** [Adyen/magento#426]
I'm getting an AUTHORISATION notification with success flag set to false. An invoice is created automatically.

**Comment by rikterbeek** [comment]
Hi TamasJozsefSzabo,

Are you using our server communication notification or the deprecate notification system ?

Regards,
Rik
Adyen

**Comment by TamasJozsefSzabo** [comment]
Hi rikterbeek,

I see an "A new notification framework is available." message on Adyen back office (and a migrate button, plus additional info) so I think we are using the deprecated notification system. Do you suggest migrating to the new one? (I guess you do.) I can try it in the test environment first. And I understand this change can be rolled back to standard notification if necessary.

**Comment by rikterbeek** [comment]
Hi TamasJozsefSzabo,

Yes please do migrate to the new system this should solve your issues. No you can't switch back because old notification is deprecate.

Regards,
Rik
Adyen
