### ISSUE TITLE
Refund on Adyen - incorrect credit memo created in Magento

### ISSUE THREAD

**Issue by maximinimus** [Adyen/magento#456]
When a refund is issued on the Adyen backend and no reference is entered, Adyen will post a notification back to Magento to create a new credit memo for the order.

This creditmemo will ignore if a creditmemo has already been created in the Magento backend and it will attempt to refund all the items in the order.

**Comment by rikterbeek** [comment]
Hi Mathew,

If you want to do a partial refund you need to do this through Magento because we don't know what items are refunded. If you still want to use Adyen platform for refunds you can set the setting "Ignore refund notification" to yes.

Regards,
Rik
Adyen
