### ISSUE TITLE
Wrong currency sent to Adyen when using Magento's currency converter.

### ISSUE THREAD

**Issue by albertdahlin** [Adyen/magento#457]
### Steps to reproduce

Setup:
* Capture delay set to manual, both in Adyen and Magento.
* Base currency SEK
* Enter currency exchange rates in Magento to enable USD in the shop.

Place an order in USD in the shop, using Adyen CC with CSE.
In this case, the order Grand Total was $64.73 (560.90 SEK in base grand total).

An authorization was created in the Adyen Backend, currency USD which is as expected.

From our test account:
![image](https://cloud.githubusercontent.com/assets/8900986/11030683/e5e9acaa-86cf-11e5-97f1-3e1dfbc18b03.png)

When I create an invoice for the order in Magento and use Capture Online, the order is not captured in Adyen due to the capture being sent in a different currency than the authorize.

![image](https://cloud.githubusercontent.com/assets/8900986/11030526/f4a2586a-86ce-11e5-8073-485b13a64b61.png)

As you can see, the order is also set to processing, which might not be correct. I would expect it to still be pending since the capture wasn't successful.

**Comment by rikterbeek** [comment]
Hi Albert,

I understand your issue. Unfortunately I don't know how we can change this. Magento will change the status to processing if an invoice is created. We can't set a pending status in this time because the Magento core does this by default. 

Regards,
Rik
Adyen

**Comment by albertdahlin** [comment]
I understand the problem with Magento setting the order to processing by default. I think I can work around this, by adding another order status.

The main issue for me is that the wrong currency is sent to Adyen when I create an invoice and use Capture Online. This prevents me from capturing manually from Magento.

**Comment by rikterbeek** [comment]
HI Albert,

This is because in the interface of the invoice Magento is converting it to the base currency. I have no idea if there is a setting in Magento to use order currency instead of base currency in the invoice view.

Regards,
Rik
Adyen

**Comment by albertdahlin** [comment]
Hello Rik,

I can confirm that this is also an issue when creating credit memos in Magento. They will be sent to Adyen in the base currency, not the currency used on authorize.

There must be a way to solve this. Magento saves all prices in both base and order currency on orders, invoices and credit memos. Also the exchange rate used is saved on the order, invoice and credit memo.

Isn't it possible to get the right currency code and amount from the invoice model saved before sending the API capture request to Adyen?

Authorize Request:
```
    [response] => Array
        (
            [originalReference] => 
            [reason] => 3694:1111:6/2016
            [additionalData_authCode] => 3694
            [additionalData_expiryDate] => 6/2016
            [additionalData_cardSummary] => 1111
            [merchantAccountCode] => xxxxxxx
            [eventCode] => AUTHORISATION
            [operations] => CANCEL,CAPTURE,REFUND
            [success] => true
            [paymentMethod] => visa
            [currency] => USD
            [pspReference] => 7914470620734539
            [merchantReference] => 100000062
            [value] => 6473
            [live] => false
            [eventDate] => 2015-11-09T09:41:13.75Z
            [additionalData] => Array
                (
                    [authCode] => 3694
                    [expiryDate] => 6/2016
                    [cardSummary] => 1111
                )

            [amount] => Array
                (
                    [value] => 6473
                    [currency] => USD
                )

        )
```

Capture Request:
```
    [processResponse begin] => Begin to process Notification
    [response] => Array
        (
            [originalReference] => 7914470620734539
            [reason] => Modification in different currency than authorisation
            [merchantAccountCode] => xxxxx
            [eventCode] => CAPTURE
            [operations] => 
            [success] => false
            [paymentMethod] => visa
            [currency] => SEK
            [pspReference] => 7914470621135074
            [merchantReference] => 100000062
            [value] => 56290
            [live] => false
            [eventDate] => 2015-11-09T09:41:53.00Z
            [amount] => Array
                (
                    [value] => 56290
                    [currency] => SEK
                )

        )
```

**Comment by rikterbeek** [comment]
Hi Albert,

The problem here is partial refunds and partial captures and option to put in a manual amount. You can define your own amount to refund as well this is in the base currency instead of the order currency. The solution here is to use the order currency in the view instead of the base currency but that is something that is in the core of magento.

Regards,
Rik
Adyen

**Comment by albertdahlin** [comment]
Or to use the `base_to_order_rate` data saved in the invoice and do the conversion before sending the refund / capture.
