### ISSUE TITLE
Order not processed when using different currency

### ISSUE THREAD

**Issue by gigadesign1** [Adyen/magento#461]
We recently added a merchant account in US Dollars to our Adyen account.
But when a order in US Dollar is placed through Adyen, it keeps 'hanging' on the status authorized.

Both our merchant account and Magento are configured to auto-capture every payment and automaticly create an invoice.
This does work for orders in Euro's, but not for orders in US Dollars.

This are our settings in the merchant account:
![schermafbeelding 2015-11-12 om 15 45 51](https://cloud.githubusercontent.com/assets/1337445/11121165/950bc6d8-8954-11e5-9fab-563ed052bc50.png)

**Comment by gigadesign1** [comment]
Possibly related to #457

**Comment by rikterbeek** [comment]
Hi Mark,

Did you configure the server communication notification in this merchant account ? this sends the notification to the magento webshop and then can update the order.

Regards,
Rik
Adyen

**Comment by gigadesign1** [comment]
No, I didn't. Hope this fixes this issue. Thanks!
