### ISSUE TITLE
Issue with multi domain stores redirect url

### ISSUE THREAD

**Issue by questionmark78** [Adyen/magento#467]
The getOrderPlaceRedirectUrl() function in Adyen_Payment_Model_Adyen_Hpp returns a url, but the store id is 0 there, so the url is that of the default store.
In our case this is the backend (admin) url which is different than the one for any store and not accessible for visitors.
Issue should be solved by using:
   public function getOrderPlaceRedirectUrl()
    {
        return Mage::getUrl('adyen/process/redirect',array('_store'=>$this->getStore()->getStoreId()));    
    }

I was not sure for which branch to create a pull request at the moment.

**Comment by rikterbeek** [comment]
Hi questionmark78,

The HPP payment method is not available for backend orders because it is a redirect what Magento does not support for backend orders. How are you using this in the backend ?

Regards,
Rik
Adyen

**Comment by questionmark78** [comment]
We are not using it in the backend, but in this code on the frontend the store_id seems to be 0 (Mage::log code added there told us so), causing the url to be the default store, which is not having a frontend in our setup.

**Comment by rikterbeek** [comment]
Hi questionmark78 ,

With Mage::getUrl(..) it is not needed to add the storeId. It will be resolved by itself so I think you have somewhere else an issue. If I look in the core Magento code they don't add an storeId as well.

Regards,
Rik
Adyen
