### ISSUE TITLE
Setting order status Adyen refund

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/magento#472]
Hi for the Setting order status Adyen refund

Is it possible to discern between full refund and partial refund?

The process behind these two is quite different and one needs to see the difference in grid and details

That would be really great.

**Comment by rikterbeek** [comment]
Hi Sean,

Yes this is something we can do. For now don't select a status if you do partial refunds so magento will automatically detect this and keep it on processing.

Regards,
Rik

**Comment by shirtsofholl** [comment]
OK sounds great, Would be great addition. Happy to see it i next version



Wij maken het graag voor je in orde.

met groeten, Mark


_________________________________________________________
info@shirtsofholland.com | KvK 60827378 | https://shirtsofholland.com

[image: ShirtsofHolland - dé specialist in Oranje kleding]
<http://shirtsofholland.com/>

2015-11-30 8:37 GMT+01:00 Rik ter Beek <notifications@github.com>:
