### ISSUE TITLE
Payment fees in 'sync' with Adyen backend settings. And taxable

### ISSUE THREAD

**Issue by newsjunk** [Adyen/magento#476]
We have some issues with the payment fees.

issue: we cannot add correct payment fees. This is very important for us, because of lots relative of small transactions.

First:  We tried an external extension to get a lot of options in regard to  payment fees. We used foomans' surcharge module.
Problem: the Adyen payment options are rendered in such a way, this module is not usable. 
I am not a magento programmers, but it has something to do with naming the payment methods.

For now, what we can do with the 'fee setting' in the Adyen module is very limited:  

Yes, You can set fees in the adyen/magento backend now. 
- but our invoices are incorrect because we cannot apply tax to this fee.
-The fee can only be a fixed amount, not a fixed amount + a percentage

Like in the Adyen ' CA- backend', we would very much like to be able to attatch a % and/or absolute price as a fee to different CC's, paypal and other payment methods.

ideally fees are constructed as follows: 

-Able to attach a fixed sum to all payment methods
-Able to attach a Percentage of the total price to all payment methods
-Fees should be taxable (as a service, 21% in The Netherlands)
-And I think fees should be named/rendered correctly so our export/import software can export this to our accountingsoftware. (But not sure about this last remark)

**Comment by rikterbeek** [comment]
Hi newsjunk,

Thanks for letting us know about your issue. I think that we need to make if it is taxable an option the same way you now have with shipping costs. We can add a tax class into the tax configuration so you can set this up(below shipping tax class). We will add this week an option to add a percentage as well to the payment methods. The last point is something on your end you need to look at we give it now a standard name "payment_fee".

Regards,
Rik
Adyen

**Comment by newsjunk** [comment]
super! will wait for it

**Comment by rikterbeek** [comment]
Hi Newsjunk,

See the commit above. I created a submodule for it called "Fee". It should contain everything you suggested. 

Regards,
Rik
Adyen

**Comment by ebaschiera** [comment]
Hello Rik,
I appreciate your work on this issue, me too I'm finding it very useful.
So how can I benefit from that commit? Should I install the develop version of the module? Will that commit merged into master? What's the release plan?
Thank you.

-Ermanno Baschiera

**Comment by rikterbeek** [comment]
Hi Ermanno,

Thanks for the appreciation. The easiest is to switch to the develop version. This week we will release 2.5.0 you can find the beta here: https://github.com/Adyen/magento/tree/release-2.5.0 but this will not contain this separate fee module. This will be in the next release there is no ETA yet.

Regards,
Rik
Adyen

**Comment by FreekVandeursen** [comment]
Hello Rik,

Do you have an estimate yet on which date the 2.6.0 version will be released? We are really looking forward to use the percentage payment fee functionality.

Best regards,

Freek Vandeursen
