### ISSUE TITLE
Improve refund authorized status

### ISSUE THREAD

**Issue by leeuwd** [Adyen/magento#482]
The 'refund authorized status' could be improved. The function `Adyen_Payment_Model_ProcessNotification::_setRefundAuthorized($order)` sets the status of the order after the creditmemo has been created. A credit memo creation sets the order state and status to 'processing' in `Mage_Sales_Model_Order_Payment::refund($creditmemo)`, see line `730`, which is default Magento behaviour. 

The line `$status = (!empty($status)) ? $status : $order->getStatus();` in `Adyen_Payment_Model_ProcessNotification::_setRefundAuthorized($order)` thus always returns 'processing' when `(!empty($status)` is `true`. I'd rather see:

```
protected function _setRefundAuthorized($order, $orderStatusBeforeProcessingRefundCallback) {
   $this->_debugData['_setRefundAuthorized'] = 'Status update to default status or refund_authorized status if this is set';
   $status = $this->_getConfigData('refund_authorized', 'adyen_abstract', $order->getStoreId());
   $status = (!empty($status)) ? $status : orderStatusBeforeProcessingRefundCallback;
   $order->addStatusHistoryComment(Mage::helper('adyen')->__('Adyen Refund Successfully completed'), $status);
   $order->sendOrderUpdateEmail((bool) $this->_getConfigData('send_update_mail', 'adyen_abstract', $order->getStoreId()));
}
```

This version uses the original order status before the callback. I thinks it is strange Magento always sets the order back to a 'processing' status.

**Comment by rikterbeek** [comment]
Hi Leeuwd,

We have now added an option to set a full refund status and partial refund status. By setting these two statuses will that solve your issue ?

Regards,
Rik
Adyen
