### ISSUE TITLE
CC details translations missing?

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#484]
Hi, not sure about this one. But it seems the CC details translations are missing. We have found similar lines in the translation files but not the exact one either in NL, DE or FR .... nor in templates ... so to be honest we dont know where it is coming from

Are the translations really missing? Or is this something we can fix easily?

![image](https://cloud.githubusercontent.com/assets/652395/11905164/06d7c69a-a5c5-11e5-80a8-9e45535a00f6.png)

**Comment by rikterbeek** [comment]
Hi Sean,

You mean Sepa titles not CC details. the bank account holder name is in the translation files. see: https://github.com/Adyen/magento/blob/develop/app/locale/nl_NL/Adyen_Payment.csv#L64
The other one is missing we will add this.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
There is a comma behind the last item, is that a problem?

"Bank account holder name","Naam rekeninghouder",

ANd of the other one, please let us know what it is: then I can provide DE
and FR too

**Comment by rikterbeek** [comment]
Hi Sean,

No that is not correct. I fix it see fix above.

Regards,
Rik

**Comment by rikterbeek** [comment]
Translation texts are added.
