### ISSUE TITLE
Should this be in exception log? Is this a code exception? Declined due to the Card Security Code(CVC) being incorrect

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#486]
Should this be in exception log? Is this a code exception? 

Declined due to the Card Security Code(CVC) being incorrect

2015-12-27T18:35:15+00:00 DEBUG (7): Exception message: Declined due to the Card Security Code(CVC) being incorrect. Please check your CVC code!
Trace: #0 /home/store/public_html/.modman/magento/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(396): Adyen_Payment_Exception::throwException('Declined due to...')
#1 /home/store/public_html/.modman/magento/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(303): Adyen_Payment_Model_Adyen_Abstract->_processResponse(Object(Mage_Sales_Model_Order_Payment), Object(stdClass), 'authorise3d')
#2 /home/store/public_html/.modman/magento/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(205): Adyen_Payment_Model_Adyen_Abstract->_processRequest(Object(Mage_Sales_Model_Order_Payment), '72.3600', 'authorise3d')
#3 /home/store/public_html/.modman/magento/app/code/community/Adyen/Payment/controllers/ProcessController.php(208): Adyen_Payment_Model_Adyen_Abstract->authorise3d(Object(Mage_Sales_Model_Order_Payment), '72.3600')
#4 /home/store/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Adyen_Payment_ProcessController->validate3dAction()
#5 /home/store/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('validate3d')
#6 /home/store/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /home/store/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#8 /home/store/public_html/app/Mage.php(705): Mage_Core_Model_App->run(Array)
#9 /home/store/public_html/index.php(105): Mage::run('store_en', 'media')
#10 {main}

**Comment by rikterbeek** [comment]
Hi Sean,

Yes this should be in the exception log because we need to return a exception otherwise this specific error message can not be shown to the customer.

Regards,
Rik
