### ISSUE TITLE
When sending emails from cron, text is not translated

### ISSUE THREAD

**Issue by oblomovx** [Adyen/magento#489]
Version 2.5
When an order is processed from the queue, the email that is sent out is not translated. I guess cron-jobs work in the admin store, so no localization is used.

**Comment by rikterbeek** [comment]
Hi oblomovx,

We let magento send the order confirmation mail so i think you have some issues with the core of magento.

Regards,
Rik

**Comment by oblomovx** [comment]
Yes, after some research I found it's an issue within magento, fixed it like described here:

http://magento.stackexchange.com/questions/25612/cron-job-template-block-not-being-translated-but-testobserver-is

**Comment by rikterbeek** [comment]
Hi oblomovx,

Great!

Regards,
Rik
Adyen

**Comment by leeuwd** [comment]
For others with the same problem: we had this issue too and fixed it by:

```php
// Get store order was placed from
$store = $order->getStore();
$localeCode = Mage::getStoreConfig('general/locale/code', $store);

// Start store emulation process
$appEmulation = Mage::getSingleton('core/app_emulation');
$initialEnvironmentInfo = $appEmulation->startEnvironmentEmulation($store->getId());

// Re-init locale to prevent/fix any wrong translations in shipment e-mail (Magento bug?!);
// cron files are run in 'admin' area and thus static blocks (and other stuff) is not properly translated
Mage::app()->getTranslator()->setLocale($localeCode)->init(Mage_Core_Model_App_Area::AREA_FRONTEND, true);
```

**Comment by mozgbrasil** [comment]
Hello

Good Morning

I am using the new version of Magento 1.9.3.2 and this problem is occurring here in my project

In which file should I place this fix?

**Comment by leeuwd** [comment]
@mozgbrasil: we've put this code in the 'createShipment()' method used in API communications with our third-party order fulfillment. 

Otherwise, I'd put it in `Mage_Sales_Model_Order_Shipment::sendEmail`, line 403. Only add this then:

```
// Re-init locale to prevent/fix any wrong translations in shipment e-mail (Magento bug?!);
// cron files are run in 'admin' area and thus static blocks (and other stuff) is not properly translated
Mage::app()->getTranslator()->setLocale($localeCode)->init(Mage_Core_Model_App_Area::AREA_FRONTEND, true);
```

**Comment by peterjaap** [comment]
We also had this problem for 7 months(!).  Couldn't find it. We were looking in the wrong direction. Thanks to this thread, we solved it. You're the hero of the day @leeuwd !

We actually had this problem in the New order email for non-default locale stores. We made a rewrite for `Mage_Sales_Model_Order` and added this piece of code in the `queueNewOrderEmail()` method after `stopEmulation`;

```
        // FIX FOR https://github.com/Adyen/adyen-magento/issues/489
        // Re-init locale to prevent/fix any wrong translations in shipment e-mail (Magento bug?!);
        // cron files are run in 'admin' area and thus static blocks (and other stuff) is not properly translated
        $localeCode = Mage::getStoreConfig('general/locale/code', $storeId);
        Mage::app()->getTranslator()->setLocale($localeCode)->init(Mage_Core_Model_App_Area::AREA_FRONTEND, true);
        // END FIX
```

**Comment by philipperaemdonck** [comment]
https://github.com/Adyen/adyen-magento/issues/489#issuecomment-274766655

Did the trick for me 🙏
