### ISSUE TITLE
Products remain in cart after sucessful checkout

### ISSUE THREAD

**Issue by LemosT** [Adyen/magento#491]
Greetings. We're still collecting more data on which situations exactly this happens, but we're getting reports that the products are not removed from the shopping cart even after a successful checkout process. Could you please look into possible causes for this?

**Comment by rikterbeek** [comment]
Hi LemosT,

I have never heard of this issue and I can't reproduce it.
I doubt this is something in our module because we let Magento create the order and then it should not be possible to view the card again after a successful payment.

Regards,
Rik
Adyen
