### ISSUE TITLE
Onetime discount code invalid when entered wrong CVC code and trying again

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/magento#492]
Onetime discount code invalid when entered wrong CVC code and trying again

Hi , we have seen some cases where a customer has a onetime discount/coupon code (default Magento). They then try to pay using Adyen CC but make a mistake, or click cancel and want to change payment method, or enter the wrong CVC code ... 

The problem is that the  discount/coupon code then does not work anymore. In the case of CVC error or changing payment method all on Adyen platform the discount/coupon code should not be invalidated ... and users should convert to paying customer

**Comment by rikterbeek** [comment]
Hi shirtsofholland,

I don't think you should address this to us. What has happened is that a order is created with the coupon code. That order is cancelled so magento should reactivate the coupon code. Have a look here how you can do this:
http://magebase.com/magento-tutorials/quick-fix-coupon-codes-used-up-on-incomplete-transactions/

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
Thanks - looks like rather old code. But I see PeterJaap made a fix too.
https://gist.github.com/peterjaap

FYI: for others that may install it ....






Wij maken het graag voor je in orde.

met groeten, Mark


_________________________________________________________
info@shirtsofholland.com | KvK 60827378 | https://shirtsofholland.com

[image: ShirtsofHolland - dé specialist in Oranje kleding]
<http://shirtsofholland.com/>

2016-01-11 8:37 GMT+01:00 Rik ter Beek <notifications@github.com>:
