### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by C-Gross** [Adyen/magento#497]
There is an error in the data upgrade scripts using the same function name which does not work on a completely new installation on a clean installed Magento 1.9.2.2

Fatal error: Cannot redeclare updateConfigValue() (previously declared in [...]/app/code/community/Adyen/Payment/data/adyen_setup/data-upgrade-2.1.2.3-2.1.2.4.php:43) in [...]/app/code/community/Adyen/Payment/data/adyen_setup/data-upgrade-2.4.0-2.4.0.1.php on line 50

It's working to run the update again, because it will continue on the 2nd data upgrade script and won't load the 1st one again but thats not a nice solution. I renamed the function on the 2nd script but would be nice to have an official update for this.

**Comment by rikterbeek** [comment]
Hi gide-cgross,

Thanks for letting us know. I have fixed it see above commit. Will be in the upcoming patch update 2.5.1.

Regards,
Rik
