### ISSUE TITLE
Not logical showing of Ideal in German stores

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#501]
Use case

1. german store
2. Ideal enabled on DC
3. selected billing country to NL (can be the case1)

Then Ideal list is populated with NO BANKS -- empty list, no banks

THis needs to be fixed, seems like some GEO Ip functionality goes against the Magento config

Expected result
- German customer has Dutch billing
- So wants to pay via Dutch method

- Now not possible

![image](https://cloud.githubusercontent.com/assets/652395/12304829/dfd69612-ba31-11e5-82c5-8e19f777691d.png)

**Comment by rikterbeek** [comment]
Hi Sean,

Are you on the latest version of our module ? In the latest version of the module IDeal will be automatically show if the result is in the directoryLookup result (call to adyen to retrieve payment methods). If you do not preset the countryCode in the settings then you should see ideal + banks if you selected Netherlands as billing address in the checkout.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
Will upgrade then ;P
