### ISSUE TITLE
Error in upgrade script

### ISSUE THREAD

**Issue by bartlubbersen** [Adyen/magento#508]
Ha,

Tijdens het installeren kreeg ik een upgrade error:

Fatal error: Cannot redeclare updateConfigValue() (previously declared in /home/experius/domains/fashiondrug.eu.dev1.xpdev.nl/.modman/module-adyen-payment/app/code/community/Adyen/Payment/data/adyen_setup/data-upgrade-2.1.2.3-2.1.2.4.php:43) in /home/experius/domains/fashiondrug.eu.dev1.xpdev.nl/.modman/module-adyen-payment/app/code/community/Adyen/Payment/data/adyen_setup/data-upgrade-2.4.0-2.4.0.1.php on line 50

Ik heb de branch release-2.5.0 gepulled op een Magento omgeving waar de module nog nooit in heeft gezeten. Nogmaals herladen loste het probleem op gezien dan het eerdere upgrade script niet nogmaals wordt uitgevoerd. Maar bij eerste keer laden krijg je dus altijd deze error.

**Comment by rikterbeek** [comment]
Hoi bartlubbersen,

Dank voor het aangeven we waren hiervan al op de hoogte via #497 
Dit is opgelost in de nieuwe release 2.5.1.

Groet,
Rik
Adyen
