### ISSUE TITLE
Pay by mail SHA1

### ISSUE THREAD

**Issue by gigadesign1** [Adyen/magento#511]
Version 2.5.0

PayByMail payment method still uses SHA1 HMAC keys, but the other payment methods use SHA256 now.

Can PayByMail also be updated to SHA256?

**Comment by rikterbeek** [comment]
Hi Mark,

See fix above this will not add it in the comment history anymore.
This will be included in the next big release (2.6.0)

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Mark,

See fix above this will use sha256 instead of the old sha1 encryption
This will be included in the next big release (2.6.0)

Regards,
Rik
Adyen
