### ISSUE TITLE
PayByMail break order comments

### ISSUE THREAD

**Issue by gigadesign1** [Adyen/magento#512]
When I use the PayByMail option a comment is added to the order with the payment link.

Since the link is really long, the comment section stretches underneath the totals of the order, making it impossible/hard to add a comment as a user.

![adyen](https://cloud.githubusercontent.com/assets/1337445/12477800/e6b50896-c031-11e5-8398-b195570b4982.jpg)

**Comment by rikterbeek** [comment]
Hi Mark,

I can understand. Unfortunately the comment history will not allow links. We need to investigate if we can move this url from the comment history into the payment information block where it is possible.

Regards,
Rik
Adyen

**Comment by gigadesign1** [comment]
It is already in the payment section of the order, so I think the comment can safely be removed.

![schermafbeelding 2016-01-21 om 11 38 33](https://cloud.githubusercontent.com/assets/1337445/12478146/9ef27f46-c033-11e5-91be-0f8957f1d1ed.png)

**Comment by rikterbeek** [comment]
Hi Mark,

Then I have already done this. I will remove it from the comment history. Thanks for letting us know.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Mark,

See fix above this will not add it in the comment history anymore.
This will be included in the 2.5.1 release.

Regards,
Rik
Adyen

**Comment by gigadesign1** [comment]
Thank you!
