### ISSUE TITLE
No way to disable automatic refund when order is canceled

### ISSUE THREAD

**Issue by nuno-robosavvy** [Adyen/magento#515]
How can I disable the automatic refund when a order is canceled in Magento?

If we change something in a order it will create a copy of the order and cancel the previous one automatically refunding the payment.

In settings there's a option to ignore refunds from Adyen->Magento but how can Magento do not send refund requests to Adyen automatically?

**Comment by rikterbeek** [comment]
Hi Nuno,

By default it will do a cancel-or-refund request to Adyen if you cancel an order in magento with a Adyen payment method used. We could make a setting that you can turn this off. What I do not understand is why you are changing the order ?

Regards,
Rik
Adyen

**Comment by nuno-robosavvy** [comment]
Hi Rik,

Sometimes customers order items that are not in stock and we propose a similar product that do not affect the total amount, usually it's the same product but with a different color, we need to edit the order to change the SKU to ship and by doing that the original order is canceled.

If you want you can merge the changed that I did, added a option on settings and on the Observer.php function it will check that variable.

Regards,
Nuno Gato
Robosavvy

**Comment by rikterbeek** [comment]
Hi Nuno,

Thanks for your explanation. Yes creating a setting that is by default set to enabled is an good solution. If you can do a PR of this that would be great.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Nuno,

I accepted your pull request see #523 

Regards,
Rik
Adyen
