### ISSUE TITLE
HPP does not show icon on payment methods

### ISSUE THREAD

**Issue by nuno-robosavvy** [Adyen/magento#516]
The image html is the following

    <img class="adyen-payment-method-icon v-middle adyen_hpp" src="https://robosavvy.com/store/skin/frontend/base/default/images/adyen/img_trans.gif" width="66" height="43" alt="Credit or Debit Card" border="0" style="-webkit-user-select: auto;">

On the css file there's no image setting for the class adyen_hpp

Solution, add class to adyenstyle.css file

**Comment by rikterbeek** [comment]
Hi Nuno,

True it is better to show that image then no issue. Could you do a pull request to the develop branch so i can merge it into our code ?

Regards,
Rik
Adyen

**Comment by nuno-robosavvy** [comment]
I'm new at github, I think I did the pull request properly.

Let me know if it's ok like that.

Regards,
Nuno Gato
--RoboSavvy

**Comment by rikterbeek** [comment]
Hi Nuno,

No problem you did it correct. I merged it into our develop branch.

Regards,
Rik
Adyen
