### ISSUE TITLE
Error on success page when using PayByMail

### ISSUE THREAD

**Issue by gigadesign1** [Adyen/magento#518]
Since HPP is SHA256 and PayByMail is SHA1, we use different skins for both payment methods.

When a customer completes a payment with the PayByMail method the verification fails, due to the fact that HMAC keys for HPP are being used for verification.
Error message; 'ResultUrl authentification failure'

I fixed this in the function '_signAuthenticate' in class Adyen_Payment_Model_Authenticate by checking what skin code was used and get the correct HMAC keys.

Hint;
<img width="777" alt="schermafbeelding 2016-01-24 om 12 41 53" src="https://cloud.githubusercontent.com/assets/1337445/12536017/e80702a4-c297-11e5-81aa-d24927d1e5ca.png">

**Comment by rikterbeek** [comment]
Hi Mark,

SHA1 is going to be deprecated in the next official version. In the develop version you already see that sha256 is used for the PayByMail see fix #511.

Regards,
Rik
Adyen

**Comment by gigadesign1** [comment]
I understand, but if the PayByMail method can still use a different skinCode, then this issue will still exsist, since the verification string will use the skinCode from the HPP method.

**Comment by rikterbeek** [comment]
Hi Mark,

No you can use the official release version that is still sha1 or the develop version that is now sha256.
In Adyen platform you can convert your sha1 skin to a sha256 skin if you want to use this develop version.

Regards,
Rik
Adyen
