### ISSUE TITLE
After upgrade to latest version HPP is completely gone (only see CC)

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/magento#521]
After upgrade to latest version HPP is completely gone (only see CC)

Is there something I missed that needed changing in between versions? Coming from 2.4

In log I am only seeing

```
Warning: pack(): Type H: illegal hex digit m  in public_html/.modman/magento/app/code/community/Adyen/Payment/Model/Observer.php on line 399

and 

Notice: Undefined index: code_alt  in public_html/.modman/magento/app/code/community/Adyen/Payment/Helper/Data.php on line 58

```

thanks!!

**Comment by rikterbeek** [comment]
Hi shirtsofholl,

What version are you using ? there is a mismatch between adyen and Magento module concerning the signature. If you are on 2.5.2 use SHA1 signature if you using develop version use SHA256 signature.

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
We issued modman update --- can this be it then?

Please tell me how to fix  ;( currently not accepting payments

**Comment by rikterbeek** [comment]
Hi shirtsofholl,

You should use the release versions and not the develop version on your live site.
What you did is just update the develop branch to the latest version. So or you switch back to stable release version see https://github.com/Adyen/magento/releases this is as well the master branch or you update your skins to SHA256.

Regards,
Rik

**Comment by shirtsofholl** [comment]
we fixed by issuing modman remove. And uploading 2.5.1. using FTP. Concerning the versions: what is the last "working" version? I dont see 2.5.2 in releases

**Comment by rikterbeek** [comment]
Hi shirtsofholl,

Latest version is 2.5.1.

Regards,
Rik
Adyen
