### ISSUE TITLE
Missing image iDeal BUNQ

### ISSUE THREAD

**Issue by ajpevers** [Adyen/magento#522]
```
File does not exist: /var/www/vhosts/coltex/httpdocs/skin/frontend/base/default/images/adyen/BUNQ.png
```

![screen shot 2016-01-27 at 10 23 59](https://cloud.githubusercontent.com/assets/1489129/12609244/eb5a8160-c4e0-11e5-814a-238dec737a2d.png)

**Comment by rikterbeek** [comment]
Hi Anton,

Logo is added. Will be in the next release 2.5.2.

Regards,
Rik
Adyen
