### ISSUE TITLE
SEPA and CC data is displayed in wrong order or subscription

### ISSUE THREAD

**Issue by sandermangel** [Adyen/magento#525]
When editing an order or subscription with SEPA data it's stored to localStorage (see [sepa.phtml](https://github.com/Adyen/magento/blob/867e7b37decd76abaacc6436c0f2906cd23f4d73/app/design/adminhtml/default/default/template/adyen/form/sepa.phtml#L84) and [cc.phtml](https://github.com/Adyen/magento/blob/4ff027d98cab5c4e2cfc8148888e48ea9db3da04/app/design/adminhtml/default/default/template/adyen/form/cc.phtml#L160)). If the next order / subscription edited does not have prepopulated SEPA data the last orders SEPA data is displayed.

**Possible solution**

Add a unique order/subscription ID to the storage key to prevent it getting retrieved on incorrect order or subscription

**Comment by rikterbeek** [comment]
Hi Sander,

Thanks for letting us know about this issue. This is in the Payment module so we can do in on a unique orderId.

Regards,
Rik
Adyen

**Comment by sandermangel** [comment]
@rikterbeek order id sounds good. Any idea on when you can get to this?

**Comment by rikterbeek** [comment]
Hi Sander,

I changed it, I used quoteId because order is not created on that moment.

Regards,
Rik
