### ISSUE TITLE
getMinorUnitTaxPercent should multiply first and then cast to int

### ISSUE THREAD

**Issue by EwaldBorger** [Adyen/magento#526]
Adyen_Payment_Helper_Data::getMinorUnitTaxPercent currently does 
```
$taxPercent = (int)$taxPercent;
return $taxPercent * 100;
```
But wouldn't it be more useful to do:
```
$taxPercent = $taxPercent * 100;
return (int)$taxPercent;
```
That way for example a tax rate of 8.25% would become 825 instead of 800

**Comment by rikterbeek** [comment]
Hi Ewald,

I agree. You can always do a pull request to our repository to fix this. I will change this now myself.

Regards,
Rik
Adyen

**Comment by EwaldBorger** [comment]
Awesome :)
I hadn't forked and such, found it while browsing the code :)
