### ISSUE TITLE
Constraint on increment id after placing a refused order

### ISSUE THREAD

**Issue by bartdelvaux** [Adyen/magento#539]
When placing an order that is refused (like iDEAL issuer REFUSED) the quote is restored to reorder it again. 
When ordering that quote again, you will get in some cases a constraint violation on the order increment id. 
This is caused because the preserved order id of the quote refers to the previously refused order. Magento checks that and increases the id if needed but this don't work in some cases. 
If you have an order increment ids prefixed with a string (like BB00002365), Magento will not increase this number because Magento requires an int. With a small fix in the `isOrderIncrementIdUsed` function of the `Mage_Sales_Model_Resource_Quote class`, this could be fixed. 

Change `$bind      = array(':increment_id' => (int)$orderIncrementId);` to `$bind = array(':increment_id' => $orderIncrementId);` with a Magento rewrite. 

This is not directly an issue with the Adyen payment module but this is an issue when you have the combination Adyen and order increment ids prefixed with a string.

**Comment by rikterbeek** [comment]
Hi Bart,

Thanks for sharing this. This is indeed a common Magento Issue when you are not using a integer for the incrementId. I will close this issue because not something we can change in our module. I will have a look if we can create a FAQ somewhere where we can add this one.

Regards,
Rik
Adyen

**Comment by bartdelvaux** [comment]
Hello Rik

Maybe it is a good idea to reset the reserved_order_id when the payment is refused. I see that there is a function for doing that but in the case of a refused payment, this function is not executed. 

This could be a workaround to avoid this problem.

**Comment by rikterbeek** [comment]
Hi Bart,

We are already doing this see: https://github.com/Adyen/magento/blob/develop/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php

Regards,
Rik
Adyen
