### ISSUE TITLE
Payment autorisation status

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/magento#540]
Payment autorisation status should be used for CC, SEPA and PayPal in case of no direct payment - but where CC or bank transfer is used in parallel (not enough money on paypal account)

Paypal payments that now use the parallel method (SEPA/CC or Bank transfer) have the status "Nog betalen" and are automatically cleaned: which is not correct .... payment may come later

![image](https://cloud.githubusercontent.com/assets/11224809/13381216/ac603272-de56-11e5-9c8f-63e7e2c58a09.png)

**Comment by rikterbeek** [comment]
Hi Shirtsofholl,

The "Payment autorisation status " is set when the AUTHORISATION notification is received. This is the case for all payment methods.

Regards,
Rik
Adyen.
