### ISSUE TITLE
ideal payment method, bank field not populated (v2.5.4)

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/magento#544]
ideal payment method, bank field not populated

see image

I recall we used to see the bank name here 

![image](https://cloud.githubusercontent.com/assets/11224809/13520302/8fa477c4-e1df-11e5-8379-d1ed609a7120.png)

**Comment by rikterbeek** [comment]
Hi Shirtsofholl,

Thanks for letting us could you be more specific where this is the case ?

Regards,
Rik

**Comment by shirtsofholl** [comment]
on the invoice



Wij maken het graag voor je in orde.

met groeten, Mark


_________________________________________________________
info@shirtsofholland.com | KvK 60827378 | https://shirtsofholland.com

[image: ShirtsofHolland - dé specialist in Oranje kleding]
<http://shirtsofholland.com/>

2016-03-04 10:41 GMT+01:00 Rik ter Beek <notifications@github.com>:

**Comment by rikterbeek** [comment]
Hi Mark,

Thanks this is now fixed see commit above.

Regards,
Rik
