### ISSUE TITLE
How did you hear about us?

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/magento#547]
Hi, we have adyen extension version 2.5.4. Her I cannot find the text "How did you hear about us?" But we do see this in our admin order entry

And we find the string in these files. 

What I dont understand is, that if adyen was updated and ALL files were overwritten ... and these template files do not exist in the current extension: how can it be shown?

and better: how can I get rid of it?

Help appreciated
```
ff "How did you hear"
./design/frontend/default/adyen/template/onestepcheckout/checkout.phtml:            <label for="id_feedback"><?php echo $this->__('How did you hear about us?'); ?></label><br>
./design/frontend/rwd/adyen/template/onestepcheckout/checkout.phtml:            <label for="id_feedback"><?php echo $this->__('How did you hear about us?'); ?></label><br>
./design/frontend/enterprise/adyen/template/onestepcheckout/checkout.phtml:            <label for="id_feedback"><?php echo $this->__('How did you hear about us?'); ?></label><br>
./locale/nl_NL_MEI2012/Idev_OneStepCheckout.csv:"How did you hear about us?",""
^C
```

![image](https://cloud.githubusercontent.com/assets/11224809/13579636/db8fe314-e49e-11e5-9c0c-2e209f848ab6.png)

**Comment by seansan** [comment]
Open table eav_attribute and search for attribute ith code "hear_about_us"
Delete the line item

Hope it helps someone else

[please close issue]

**Comment by shirtsofholl** [comment]
And dont know how it got there - might also NOT be adyen but other
extension.



Wij maken het graag voor je in orde.

met groeten, Mark


_________________________________________________________
info@shirtsofholland.com | KvK 60827378 | https://shirtsofholland.com

[image: ShirtsofHolland - dé specialist in Oranje kleding]
<http://shirtsofholland.com/>

2016-03-07 20:45 GMT+01:00 seansan <notifications@github.com>:

**Comment by rikterbeek** [comment]
Hi All,

This is not something from our current extension. /adyen/template/onestepcheckout/checkout.phtml could be legacy code from a really old version of us that is not needed anymore.

Regards,
Rik
Adyen
