### ISSUE TITLE
exception 'Adyen_Payment_Exception' with message '3D secure went wrong'

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/magento#549]
exception 'Adyen_Payment_Exception' with message '3D secure went wrong'

Maybe make it a little more elaborate: "what" went wrong?

**Comment by rikterbeek** [comment]
Hi Sean,

I think the url is just filled in into the browser regardless doing a payment at all.
I added some extra info into the exception so you can see if he has an order and if the result of the payment api was 3D secure payment.

Regards,
Rik
Adyen
