### ISSUE TITLE
Betaling is mislukt. Reden validation 174 Unable to decrypt data

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#552]
We are seeing error "validation 174 Unable to decrypt data"

Is this something we can solve? or is the customer doing something wrong? (if yes, then what)

Appreciate your help

Betaling is mislukt.
Reden
validation 174 Unable to decrypt data

**Comment by rikterbeek** [comment]
Hi sean,

Could you provide me with some more information about this payment. What browser is used and what device? Do you have a timeframe when it occur and do you have a merchantRefence?

Regards,
Rik

**Comment by seansan** [comment]
14 mrt. 2016 11:13:34 / it was approved later, so have to dive into the
flow for the errors 1414579490566413

Chrome

**Comment by rikterbeek** [comment]
Hi Sean,

Do you have more details about this?

Regards,
Rik
Adyen

**Comment by seansan** [comment]
there is payment ID in last update

**Comment by rikterbeek** [comment]
Hi Sean,

This payment has gone through and is processed on your account. If you have further questions about the payment you can contact our support on magento@adyen.com or support@adyen.com.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
Still we did see this error message. Should we see it?






Sent from my iPhone.

On 19 Apr 2016, at 14:34, Rik ter Beek <notifications@github.com> wrote:

Hi Sean,

This payment has gone through and is processed on your account. If you have further questions about the payment you can contact our support on magento@adyen.com or support@adyen.com.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Sean,

If you want to know the bottom of this please contact our support they can dig into the payment request and response.

Regards,
Rik
Adyen

**Comment by jj-mike** [comment]
We also get this error message, but for only around 1% of transactions.

What is the best way to determine the cause?

**Comment by rikterbeek** [comment]
Hi @jj-mike,

Please use our latest version of the module. Here the browser details are logged if this error occur. then please check with the same browser/device if you have any javascript errors in your checkout this could 
conflict with our encryption script.

Regards,
Rik
Adye

**Comment by jj-mike** [comment]
Hi @rikterbeek 

We are using Extension version 2.6.0, is this the latest?

Thanks
Mike

**Comment by rikterbeek** [comment]
Hi @jj-mike,

That version has it as well see: https://github.com/Adyen/magento/blob/2.6.0/app/code/community/Adyen/Payment/Model/Adyen/Data/PaymentRequest.php#L238

Regards,
Rik
Adyen
