### ISSUE TITLE
fatal error on Billing Agreement inserts on Magento 1.7

### ISSUE THREAD

**Issue by ebaschiera** [Adyen/magento#557]
Hi,
I'm having some issues on older magento installations (like 1.7.0.2).
In Adyen_Payment_Model_Resource_Billing_Agreement:40 the module performs a insertIgnore(), but in those old magento installations, there is not such method in Varien_Db_Adapter_Pdo_Mysql.
How can that issue be fixed?

Thanks!
-Ermanno Baschiera

**Comment by rikterbeek** [comment]
Hi Ermanno,

I did a fix so 1.7 will use a insert instead of insertIgnore that does not exsists.

Regards,
Rik
Adyen

**Comment by ebaschiera** [comment]
Awesome! Thanks!
