### ISSUE TITLE
No Doku payments logo

### ISSUE THREAD

**Issue by benzi1984** [Adyen/magento#564]
There is no Doku payments logos when using directory lookup. 
Refer to screenshot. The same goes for the plugin for Magento 2. 

I would suggest to dynamically pull the logo images from our Adyen servers. 

Test: https://test.adyen.com/hpp/img/pm/<brandCode>.png
Live: https://live.adyen.com/hpp/img/pm/<brandCode>.png

Another thing to note is that "doku_atm_mandiri_va_lite.png" is missing from the URLs above. If the codes are changed to dynamically pull logo images, do update our image libraries on both TEST and LIVE.

![screen shot 2016-04-07 at 2 02 38 pm](https://cloud.githubusercontent.com/assets/18161698/14342625/9530597a-fccd-11e5-9b40-bf5a041b47ec.png)

**Comment by rikterbeek** [comment]
Hi Ben,

I will add the images. Reason why we don't do this is because Absolute path is slower then a relative path. And with relative path the customer has an option to overwrite the image in the theme if he wants to.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Ben,

doku_atm_mandiri_va_lite.png does not exists on our site.
I have created a fallback if image does not exists to load it from adyen side.

Regards,
Rik

**Comment by benzi1984** [comment]
Hi Rik, 

I added all 4 Doku images pulled from our servers. 

The doku.png should be doku_wallet.png. 
doku_atm_mandiri_va_lite.png exists as doku_atm.png on our site. 

The hpp.php doesn't pull the doku_atm_mandiri_va_lite.png from magento folders even though it can't find it on Adyen server, and I have added it to the magento image folders.

**Comment by rikterbeek** [comment]
Hi Ben,

The images are not in our directory so If you want this to be added please do pull request.

Regards,
Rik
Adyen
