### ISSUE TITLE
Billing Agreements not added after successful payment

### ISSUE THREAD

**Issue by benzi1984** [Adyen/magento#565]
Payment was made via API(CSE) and OneClick settings on Magento has been enabled. 
OneClick settings also enabled on Adyen backoffice. 

However, on subsequent payment as the same shopper, no saved payment was pulled up for the payment. Checking the Billing Agreements under Magento showed no billing agreements have been added.

**Comment by rikterbeek** [comment]
Hi Ben,

I think you don't have the recurring contract setup for your account. Please contact magento@adyen.com with your merchantAccount and then we can turn this on.

Regards,
Rik
Adyen
