### ISSUE TITLE
payment notifications since on cron, a lot slower and customers ask questions

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/magento#567]
Hi, I understand notifications / payments processing was moved to cron

this gives a new problem because clients expect a confirmation straight away

If you use adyen and also magento with the queue

it can sometimes really take quite some time before the order is confirmed *status new

and even more time before the email is sent

we see in the backend that the order / payment is autorised

but the order has not yet moved to new

can we speed this up? (so the confirmation is received faster and the order is processed faster)

thanks

**Comment by rikterbeek** [comment]
Hi Shirtsofholl,

Make sure you have the cron running every minute. Now 5 minutes after notification receival it will be processed. If you want this faster you could change it to less minutes.
https://github.com/Adyen/magento/blob/master/app/code/community/Adyen/Payment/Model/ProcessNotification.php#L1353

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
is a delay really necessary? (anyways) I mean why have a delay?


met groeten, Mark


_________________________________________________________
info@shirtsofholland.com | KvK 60827378 | https://shirtsofholland.com

[image: ShirtsofHolland - dé specialist in Oranje kleding]
<http://shirtsofholland.com/>

2016-04-08 20:11 GMT+02:00 Rik ter Beek <notifications@github.com>:

**Comment by rikterbeek** [comment]
Yes that is why we have build it. It depends on how fast your server is how long the delay should be. But limit the notification from 5 minutes to 1 should be possible.

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
our server is rocket fast

the problem here is not technical

is is clients: that see emails coming from bol.com and amazon.com within 1
second confirming an order (and thus payment)

but all orders through an adyen/magento system can take between 5-10
minutes .... and this is confusing (and too long)

Hope it helps



Wij maken het graag voor je in orde.

met groeten, Mark


_________________________________________________________
info@shirtsofholland.com | KvK 60827378 | https://shirtsofholland.com

[image: ShirtsofHolland - dé specialist in Oranje kleding]
<http://shirtsofholland.com/>

2016-04-14 21:58 GMT+02:00 Rik ter Beek <notifications@github.com>:

**Comment by rikterbeek** [comment]
Hi,

That is nice but not all of our merchants have this and it causes issues. Limit it down to 1 should be working for everybody so that is something we will do. Immediate is not a solution because of limitation of the magento platform. 

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
I agree not "all" of our merchants would have this ....



Wij maken het graag voor je in orde.

met groeten, Mark


_________________________________________________________
info@shirtsofholland.com | KvK 60827378 | https://shirtsofholland.com

[image: ShirtsofHolland - dé specialist in Oranje kleding]
<http://shirtsofholland.com/>

2016-04-14 22:05 GMT+02:00 Rik ter Beek <notifications@github.com>:

**Comment by rikterbeek** [comment]
It is limit down to 1 minute.

Regards,
Rik
Adyen
