### ISSUE TITLE
Notice: unserialize(): Error at offset 0 of 4 bytes // Payment/Block/Form/Abstract.php

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/magento#568]
We sometimes see this error only occasionally

2016-04-13T06:39:58+00:00 ERR (3): Notice: unserialize(): Error at offset 0 of 4 bytes  in app/code/community/Adyen/Payment/Block/Form/Abstract.php on line 75

do we need to add a check here to? or is something else wrong?

**Comment by rikterbeek** [comment]
Hi,

We will look into this. I think we can improve this check.

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
thanks

any news on an intermediate release= 2.5.5



Wij maken het graag voor je in orde.

met groeten, Mark


_________________________________________________________
info@shirtsofholland.com | KvK 60827378 | https://shirtsofholland.com

[image: ShirtsofHolland - dé specialist in Oranje kleding]
<http://shirtsofholland.com/>

2016-04-14 21:57 GMT+02:00 Rik ter Beek <notifications@github.com>:

**Comment by rikterbeek** [comment]
Added extra check if getPoNumber() has an value. I don't know if your error notice is going away because maybe you have an issue with unserialize() function. This function is only used for sepa api payments so check if this payment method works on your side.

Regards,
Rik
Adyen
