### ISSUE TITLE
Pending payment

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/magento#573]
We have german payment bankTransfer_DE that does not seem to respect the setting in the backend payment pending (see screenshot)

Now orders are auto cancelled because different status is applied

ALL payments that have a pending situation .... like
- paypal when there is not enough funds
- SEPA
- all bank transfers of all countries 
- other methods where a payment is made and almost certainly is coming, only we need to wait
need to follow and set this status pending payment

pspReference: 4714609095022818 
paymentMethod: bankTransfer_DE

![image](https://cloud.githubusercontent.com/assets/11224809/14601728/1a9437aa-0564-11e6-979d-81f6bc66946b.png)

![image](https://cloud.githubusercontent.com/assets/11224809/14601877/f0044eac-0564-11e6-8901-7901eb22a5c8.png)

**Comment by rikterbeek** [comment]
Hi shirtsofholl,

Please check if you have the setting set for all your stores. 
What version of our module do you use ?
Please check your logs as well. In the code here the status is set:
https://github.com/Adyen/magento/blob/develop/app/code/community/Adyen/Payment/Model/ProcessNotification.php#L1250-L1267 

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
all stores,DC
2.4.4

the screenshot is from this setting payment_adyen_order_process_pending_status

so seems other setting

**Comment by rikterbeek** [comment]
Hi Shirtsofholl,

The setting is the same: payment/adyen_abstract/pending_status
But this setting is only applied when notification with PENDING is received. In your screenshot it is a resultUrl we don't set status based on resultUrl we use the notification.

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
I dont understand (*too technical)

A German customer buys in our store
and chooses bank transfer

what does or doesnt resulturl have to do with it?







Wij maken het graag voor je in orde.

met groeten, Mark


_________________________________________________________
info@shirtsofholland.com | KvK 60827378 | https://shirtsofholland.com

[image: ShirtsofHolland - dé specialist in Oranje kleding]
<http://shirtsofholland.com/>

2016-04-18 13:35 GMT+02:00 Rik ter Beek <notifications@github.com>:

**Comment by rikterbeek** [comment]
Hi Mark,

The setting you referring to will set this status when a notification PENDING is received from the Adyen platform. You need to configure your merchantAccount so the pending notification are send to your platform this is not done by default. You can do this by going into the adyen backoffice go to system -> server communication and here add the BankTransfer Pending Notification. The url and username/password combination needs to be the same as the standard notification.

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
Should this not be in the "Standard Notification": why is all this extra configuration necessary?

**Comment by rikterbeek** [comment]
Hi shirtsofholl,

It is not in the "Standard Notification". Yes that is possible but you need to configure the BankTransfer Pending Notification. 

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
In a previous comment from you I read: "The only thing we can do is add
generic pending notification for you then you will get updates for *all
payment methods when they are pending*. Then on the pending notification we
can build in a check if PayPal account use pending status."

question: so would adding generic pending notification not solve it for ALL
payments methods? SEPA, paypal, transfer?



Wij maken het graag voor je in orde.

met groeten, Mark


_________________________________________________________
info@shirtsofholland.com | KvK 60827378 | https://shirtsofholland.com

[image: ShirtsofHolland - dé specialist in Oranje kleding]
<http://shirtsofholland.com/>

2016-04-20 8:20 GMT+02:00 Rik ter Beek <notifications@github.com>:
