### ISSUE TITLE
Function reactivateQuote missing

### ISSUE THREAD

**Issue by bartdelvaux** [Adyen/magento#576]
In config.xml, the method reactivateQuote is called for class Adyen_Payment_Model_Observer.

This method is missing in that class. It gives a warning when your are using Magento developer mode

**Comment by rikterbeek** [comment]
Hi Bart,

Thanks for letting us know. Does this solve your issue ?

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Bart,

Issue is fixed with commit above.

Regards,
Rik
Adyen
