### ISSUE TITLE
Translation file Adyen_Payment.csv is not loaded

### ISSUE THREAD

**Issue by bartdelvaux** [Adyen/magento#579]
In the 2.6 version, the translation file for Adyen_Payment is not loaded. 

This comes because the translation file of Adyen_Payment is used in the Adyen_Fee module. When changing links 182 and 186 to Adyen_Fee in app/code/community/Adyen/Fee/etc/config.xml, the issue is solved. 

Is it possible to do this fix in a new release (2.6.1). We uses composer to load the module and version 2.6.0 is already cached in the composer repositories.

**Comment by rikterbeek** [comment]
Hi Bart,

Thanks I see the issue indeed. Quick fix is disable the fee module. I will do a fix of this and will release it later today let me know if you have other issues as well then we can include them.

Regards,
Rik

**Comment by rikterbeek** [comment]
Hi Bart,

2.6.1 is released with translation fix.

Regards,
Rik
Adyen
