### ISSUE TITLE
New order after pos payment has the wrong status

### ISSUE THREAD

**Issue by rklerck** [Adyen/magento#580]
I'm trying to implements the POS payment on my magento website, so I created a new order status (pending payment) on which the order should be set when it is created. After the payment is finished it should be processing or canceled. But it still gets the status 'Pending', before the payment is even finished.

Looks like a bug?

**Comment by rikterbeek** [comment]
Hi Rick,

Could you send me the comment history of the order so I can see where it is going wrong on your side ? If you not want this to be public shared please send us this to magento@adyen.com. 

Regards,
Rik
Adyen

**Comment by rklerck** [comment]
There is no comment history, it is directly created as a pending order.
I've set the "Order status: order creation" to "Pending Payment".

I'm also not sure of you would want a new order before the payment is processed. The user receives an email of the order before the order is fully finished. I think its confusing for the user.

**Comment by rikterbeek** [comment]
Hi Rick,

In my test side the correct status that i defined is used. What version of our extension and magento are you using? The order confirmation is only send when the payment was succesfull. The order is created otherwise the payment can not be made.

Regards,
Rik
Adyen

**Comment by rklerck** [comment]
I cloned the develop branche of magento on 05-04-2016, don't know how to see the exact version? The version in the module.xml of the adyen extension is 1.2.1.

I tested it again from a fresh start. The order is created with status pending and the confirmation is send directly (before the payment is finished).. Should I configure this differently? I kept everything default.

**Comment by rikterbeek** [comment]
Hi Rick,

There is no module.xml file in the magento1 extension. I think you mean our magento2 extension ?
https://github.com/Adyen/adyen-magento2

Regards,
Rik
Adyen

**Comment by rklerck** [comment]
wow, yes, i mean the magento 2 extension! Thought this was the right repository.. I will close this one and open another!
