### ISSUE TITLE
Bug magento adyen, is not reading CSV translation, version 2.6.1

### ISSUE THREAD

**Issue by reportingcompegps** [Adyen/magento#584]
There is a bug is not reading Adyen_Payment.csv translations.

When function  public function getFormFields()

is executed, or if you do a simple test like this:

<?php
ini_set('display_errors', '1');
include_once('../app/Mage.php');   
Mage::app('es');

echo  Mage::helper('adyen')->__("Account Number");

is not translated to spanish

I tried to debug it, but I don't know why translation of Spanish literals, is not read

app\locale\es_ES\Adyen_Payment.csv

We are using last version of Magento Adyen module version 2.6.1

**Comment by rikterbeek** [comment]
Hi @reportingcompegps ,

Sorry for the late reply. Thanks for letting us know about this issue. Does the above fix solve your issue ?

Regards,
Rik
Adyen

**Comment by lortizcompegps** [comment]
I tried it, but it doesn't fix it. With my little test

**Comment by rikterbeek** [comment]
Hi @lortizcompegps,

Maybe you are running in developersmode or your code is just not correct.

I used:

$locale = 'es_ES';
Mage::app()->getLocale()->setLocaleCode($locale);
Mage::getSingleton('core/translate')->setLocale($locale)->init('frontend', true);

echo Mage::helper('adyen')->__("Account Number");

And that was working.

Regards,
Rik
Adyen

**Comment by lortizcompegps** [comment]
yes now it works!
