### ISSUE TITLE
Percentage fee in emails v2.6.1

### ISSUE THREAD

**Issue by Exelicer** [Adyen/magento#585]
Adyen is adding percentage fee calculation to order emails even if the settings are set to 0.

in Adyen_Fee_Block_Sales_Order_Totals
the 2nd addTotal (line 53)  has no check if a fee is set

should be like:
if (((float)$this->getSource()->getPaymentPercentageFee()) != 0) {
....
}

**Comment by rikterbeek** [comment]
Hi @Exelicer,

Thanks for letting us know. You can always add a pull request with the change ;) 
I added the check if there is an value. Could you validate if this solves your issue ?

Regards,
Rik
Adyen

**Comment by Exelicer** [comment]
Yes thats fine.
