### ISSUE TITLE
Test web service credentials buttons don't obey configuration scope

### ISSUE THREAD

**Issue by ebaschiera** [Adyen/magento#586]
Hi,
if I set web service credentials per website or per store view, the buttons "Test Web Service Credentials for test" and "Test Web Service Credentials for live" don't send the correct credentials configured in the scope. They always test the auth with the default credentials.

**Comment by rikterbeek** [comment]
Hi @ebaschiera,

Thanks for letting us know. I see that you have pushed a commit to this issue did that solve your issues ?

Regards,
Rik
Adyen

**Comment by ebaschiera** [comment]
Hi Rik,
yes, my commit resolves that issue. I needed to fix it to test a particular combination of merchant accounts and websites.

-Ermanno

**Comment by rikterbeek** [comment]
Hi @ebaschiera,

Thanks for the changes looks good. Next time please do a Pull Request so I can just merge it into our code.

Regards,
Rik
Adyen
