### ISSUE TITLE
 Title for iDeal is not manageable in back office

### ISSUE THREAD

**Issue by Xebi4i** [Adyen/magento#587]
![image](https://cloud.githubusercontent.com/assets/3149168/15212717/0c64fda0-184b-11e6-9605-2fcaf295d3f9.png)
In Magento BackOffice the setting for iDeal title has been commented and becomes not manageable.
Module version - 2.6.1

**Comment by rikterbeek** [comment]
Hi Xebi4i,

It is getting the name from the payment method title. This title can be modified on adyen side. By going into Adyen Backoffice go into your skin and select for Edit Language Files here you can change the title name of the payment method. For more information please send a mail to magento@adyen.com

Regards,
Rik
Adyen

**Comment by Xebi4i** [comment]
Thank you guys. You are great.

On May 17, 2016, at 13:30, Rik ter Beek <notifications@github.com> wrote:

Hi Xebi4i,

It is getting the name from the payment method title. This title can be modified on adyen side. By going into Adyen Backoffice go into your skin and select for Edit Language Files here you can change the title name of the payment method. For more information please send a mail to magento@adyen.com

Regards,
Rik
Adyen
