### ISSUE TITLE
HMAC keys SHA function

### ISSUE THREAD

**Issue by marcatos** [Adyen/magento#591]
In commit 3a0592f8db0b0d9cd95d4e531b211f6fbe909fdd the sha algorithm was updated from sha-1 to sha-256 but backend tooltip still indicate the magento module only supports old sha-1 ([link](https://github.com/Adyen/magento/blob/2.6.1/app/code/community/Adyen/Payment/etc/system.xml#L934)).

It would be nice to select optionally between two options to gracefully support old configurations, by default using sha-1.

**Comment by rikterbeek** [comment]
Hi Simone,

Thanks for letting us know. The tooltip is updated see commit above. The SHA-1 will not be supported by Adyen from the first of Juli so please upgrade your skins to SHA-256 and use our latest version of the module. 

Regards,
Rik
Adyen
