### ISSUE TITLE
Payment percentage fee tax and payment fee amount creditmemo

### ISSUE THREAD

**Issue by leonhelmus** [Adyen/magento#593]
The first time we credit a order we allready give the full amount back even if we don't credit the full amount. Is there a possibility to adjust this. Also if we do a second credit on the same order he will pay the payment fee an extra time even though we allready refunded the credit amount. This should not be happening i believe.

**Comment by rikterbeek** [comment]
Hi @leonhelmus,

Thanks for letting us know. I see the issue it should work the same as shipping costs we will have a look how we can change this.

Regards,
Rik
Adyen

**Comment by leonhelmus** [comment]
ah k let me know when this is fixed we want to implement it this week if possible

**Comment by leonhelmus** [comment]
is it also possible to give payment fee or percentage back if the creditmemo is fully credited instead of if we make an creditmemo it will allways credit the payment fee or percentage on first creditmemo even though it wasnt fully credited.

**Comment by leonhelmus** [comment]
Or that we can assign how much we want to refund in payment percentage / payment amount

**Comment by leonhelmus** [comment]
Has there allready been made any changes to this ticket ? I would still like this functionality or bugfix. That would be very much appriciated

**Comment by rikterbeek** [comment]
Hi @leonhelmus,

I am looking into it. I have it made available so you can edit the amount. To keep the already refunded payment fee amount subtracted if you are going to do a next partial refund this is not going to be easy and there is no generic way for this as it looks like.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @leonhelmus,

The payment fee is now adjustable in the credit memo and support partial refunds.

Regards,
Rik
