### ISSUE TITLE
Invoice email (deprecated)

### ISSUE THREAD

**Issue by Maikel-Koek** [Adyen/magento#597]
Hi Rik,

The config says this field is deprecated, but it's still used in ```Adyen_Payment_Model_ProcessNotification```.

So it's not really deprecated? Will it be deprecated?

**Comment by rikterbeek** [comment]
Hi Maikel,

It is going to be deprecate. Is this a setting you use, if yes where do you use it for ?

Regards,
Rik
Adyen

**Comment by Maikel-Koek** [comment]
Yes, we use it to send the invoice email to the customer when the invoice is created, just what is says it's for.

**Comment by rikterbeek** [comment]
@Maikel-Koek,

Alright then let's remove the deprecate status and we let it in the module.

Regards,
Rik
Adyen
