### ISSUE TITLE
CanCancel payment request (payment link)

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#611]
We would like to be able to cancel payment link orders. Now they have the status "Pending Payment" indefinately. Some clients phone us and tell us that they do not understand the pay.shtml screen (mostly elderly) so they transfer the money directly .... 

the problem is that we cannot manually set the order status to
- paid
- or cancelled and then reorder

problem: when we select cancel the reply is The order(s) cannot be canceled + the cancel button is missing

https://live.adyen.com/hpp/pay.shtml
shop payment ID for example; 800001435

1) please add the ability to cancel these orders

2) also as general feedback, maybe it would be smart to CSS upgrade the HPP / https://live.adyen.com/hpp/pay.shtml payment page. People do get lost here.

**Comment by rikterbeek** [comment]
Hi Sean,

1) Yes that should be possible by using the pending status instead of the payment review status.
2) this page is totally customzible for our clients see our skin manual: https://docs.adyen.com/developers/hpp-manual#gettingstartedwithcustomisations

Regards,
Rik
Adyen


Regards,
Rik
Adyen

**Comment by seansan** [comment]
On 1) OK thanks. I assume this is in settings you mean?

2) OK. Maybe an idea to also 'per default' upgrade the CSS a little? (so
the default looks nicer too by default)

**Comment by rikterbeek** [comment]
Hi Sean,

You can now cancel an PayByMail order.
The default look and feel is in my opinion good enough as a default. We want to push our merchants to upgrade this with their own look and feel of their website instead of using our default skin.

Regards,
Rik

**Comment by seansan** [comment]
>> The default look and feel is in my opinion good enough as a default. We
want to push our merchants to upgrade this with their own look and feel of
their website instead of using our default skin.

.... do they really need pushing?

Have you seen the Mollie interface?
