### ISSUE TITLE
"transaction_id" is missing in invoice entry, which leads to no "refund" button. 

### ISSUE THREAD

**Issue by crossgate9** [Adyen/magento#612]
Hi there,

We ~~are~~ recently ~~update~~ _updated_ the module to 2.6.2 with the tagged branch in this repo. 

For Adyen_HPP, we have a problem with "Refund" button, as no transaction_id was saved to invoice entry. If we use the pspreference for "transaction_id" (copied manually), everything will be fine. 

From the order's history comment, the order status changed as following:
1. Pending, received "authored" status from Adyen;
2. Processing, invoiced created and captured online;
3. Processing, notification from "process/ins" is processed by cron job;

As we have an auto-invoice logic also via cron job, which is fine btw with the previous Adyen module, probably 2.1.2. (I think there's no event queue before.)

So I wonder, whether the problem can be resolved by swapping step 2 and 3. 
Otherwise, we may need to change part of Adyen's module code to copy the pspreference to "transaction_id", which actually we're not willing to change anything related with an official payment module. 

Thanks in advance.

Cheers,
Allen

**Comment by rikterbeek** [comment]
Hi @crossgate9,

Online refunds should just work for Adyen_HPP payements. There is set a TransactionId set on the invoice so I do not see the issue. We setting it as 1 but we can change this to the pspReference.

Regards,
Rik
Adyen

**Comment by crossgate9** [comment]
@rikterbeek , 

Nice! Thanks a lot.

BTW, what's the purpose to only set "1" for TransactionId? And will the changes be included in the next release?

Thanks,
Allen

**Comment by rikterbeek** [comment]
Hi @crossgate9,

We set here to 1 so magento knows it can be refunded online. 
Yes will be included in next release.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @crossgate9,

See commit above. Will be in the next release we do not have a release date scheduled.

Regards,
Rik
Adyen
