### ISSUE TITLE
SHA1 still used

### ISSUE THREAD

**Issue by troggybrains** [Adyen/magento#614]
Not sure if it was left on purpose or by accident but while inspecting Release 2.6.2 I could find a place where SHA1 is still being used. Please have a look at `Adyen_Payment_Model_Process::processCashResponse()`, line 61 to be specific. Shouldn't this be changed as it was changed in e.g. `Adyen_Payment_Model_Authenticate::_signAuthenticate()` (line 80)?

Additionally I'd advocate having a helper method that computes the hash from the secret word and signing data instead of duplicating the code in arbitrary places as this would make future changes easier.

**Comment by rikterbeek** [comment]
Hi @troggybrains,

Thanks for letting us know. This is legacy code the cash payment method is now using API integration so this is not needed anymore. I removed it from the code.

Regards,
Rik
Adyen
