### ISSUE TITLE
Fatal error on Billing agreement page when cart is empty

### ISSUE THREAD

**Issue by ebaschiera** [Adyen/magento#620]
Hi,
I noticed that if I login into the ecommerce website, have empty cart, and visit the Billing Agreement page, I get a fatal error.
The problem lies in Adyen_Payment_Model_Adyen_Cc::isAvailable() and Adyen_Payment_Model_Adyen_Hpp::isAvailable() methods. Apparently the $quote parameter, when null, triggers the bug.

**Comment by rikterbeek** [comment]
Hi @ebaschiera,

Thought it should always have a quote but good to check indeed. Could you do a pull request to the develop branch? then I will merge your code into the branch and will it be included in the next release.

Regards,
Rik
Adyen
